### ISSUE TITLE
Bigtable modify_column_families FailedPreconditionError: 9:Cannot relax pure age-based GC for a replicated family

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#10829]
#### Summary

Previously, the test successfully updated an existing table's column_families without an error.

Now, attempting to update an existing table's column_families without passing an explicit GC rule raises the error: "Cannot relax pure age-based GC for a replicated family"

#### Environment details

  - OS: OS X
  - Ruby version: 2.7.2 and 3.0.0
  - Gem name and version: google-cloud-bigtable

#### Steps to reproduce

[acceptance/bigtable/column_family_test.rb:108](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigtable/acceptance/bigtable/column_family_test.rb#L104-L110)

#### Full backtrace

```sh
Google::Cloud::Bigtable::Table::column_families::bigtable#test_0005_updates a column family without gc_rule:
Google::Cloud::FailedPreconditionError: 9:Cannot relax pure age-based GC for a replicated family (cf1). If you must relax the age constraint, unreplicate the instance and try again.. debug_error_string:{"created":"@1615233838.381525000","description":"Error received from peer ipv4:172.217.14.106:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Cannot relax pure age-based GC for a replicated family (cf1). If you must relax the age constraint, unreplicate the instance and try again.","grpc_status":9}
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb:736:in `rescue in modify_column_families'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb:702:in `modify_column_families'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:356:in `modify_column_families'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:215:in `column_families'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/column_family_test.rb:108:in `block (2 levels) in <top (required)>'
```

**Comment by quartzmo** [comment]
See https://cloud.google.com/bigtable/docs/garbage-collection#changes
