### ISSUE TITLE
BigQuery: NoMethodError (undefined method `each' for nil:NilClass)

### ISSUE THREAD

**Issue by scttnlsn** [googleapis/google-cloud-ruby#10881]
#### Environment details

  - OS: Ubuntu 18.04
  - Ruby version: 2.7.2p137
  - Gem name and version: google-cloud-bigquery (1.29.0)

#### Steps to reproduce

  1. Set `BIGQUERY_PROJECT` and `BIGQUERY_CREDENTIALS` environment variables (I'm setting `BIGQUERY_CREDENTIALS` to the contents of my JSON credentials file) 
  2. Run the code example below

#### Code example

```ruby
require 'google/cloud/bigquery'
bigquery = Google::Cloud::Bigquery.new
bigquery.query('SELECT 1')
```
(same error w/ any SQL I provide)

#### Full backtrace

```sh
irb(main):001:0> require 'google/cloud/bigquery'
=> true
irb(main):002:0> bigquery = Google::Cloud::Bigquery.new
=> #<Google::Cloud::Bigquery::Project:0x000055b076251234 @service=Google::Cloud::Bigquery::Service(<project name>)>
irb(main):003:0> bigquery.query('SELECT 1')
Traceback (most recent call last):
       16: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/serializer.rb:44:in `block in <module:Representable>'
       15: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/hash.rb:34:in `to_hash'
       14: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable.rb:45:in `create_representation_with'
       13: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable.rb:70:in `representable_map!'
       12: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable.rb:51:in `call'
       11: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable.rb:51:in `each'
       10: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable.rb:53:in `block in call'
        9: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/binding.rb:32:in `compile_fragment'
        8: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `call'
        7: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `inject'
        6: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:9:in `each'
        5: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:10:in `block in call'
        4: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:18:in `evaluate'
        3: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:47:in `call'
        2: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:47:in `tap'
        1: from /home/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/representable-3.0.4/lib/representable/pipeline.rb:48:in `block in call'
NoMethodError (undefined method `each' for nil:NilClass)
irb(main):004:0> 
```

I believe I'm authenticated b/c I can run `bigquery.datasets.count` and I get back the correct number

**Comment by taylorthurlow** [comment]
I'm running into the same exception but when uploading to a google cloud storage bucket. Some low-level dependency broke. Investigating now.

**Comment by taylorthurlow** [comment]
Ok traced it to a regression in `declarative-option` 0.1.1, someone beat me to the issue report here: https://github.com/apotonick/declarative-option/issues/6

**Comment by quartzmo** [comment]
[declarative-option 0.1.1 was yanked](https://github.com/apotonick/declarative-option/issues/6#issuecomment-801098877), so clean installs (and reinstalls after uninstalling declarative-option 0.1.1) should no longer have this issue.

**Comment by quartzmo** [comment]
@taylorthurlow Thanks for tracking down the source of this! Much appreciated.
