### ISSUE TITLE
chore: GHA CI error: undefined method `each' in toys/ci.rb

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#11152]
The GHA CI is encountering an error in `toys/ci.rb`. See the jobs in #11148, for example [2348539554](https://github.com/googleapis/google-cloud-ruby/pull/11148/checks?check_run_id=2348539554).

```
Run toys ci -v --only --test --github-event-name=pull_request --github-event-payload=/Users/runner/work/_temp/_github_workflow/event.json
[2021-04-15 01:12:29  INFO]  ["git", "show", "--no-patch", "--format=%H", "f3644ddd430ccc0868f634bcd5dc4a0affaac49a"]
Evaluating changes.
Getting commits from pull_request event
Diffing from base ref: f3644ddd430ccc0868f634bcd5dc4a0affaac49a
[2021-04-15 01:12:29  INFO]  ["git", "fetch", "--depth=1", "origin", "f3644ddd430ccc0868f634bcd5dc4a0affaac49a:refs/temp/f3644ddd430ccc0868f634bcd5dc4a0affaac49a"]
Fetching ref: f3644ddd430ccc0868f634bcd5dc4a0affaac49a
From https://github.com/googleapis/google-cloud-ruby
 * [new ref]         f3644ddd430ccc0868f634bcd5dc4a0affaac49a -> refs/temp/f3644ddd430ccc0868f634bcd5dc4a0affaac49a
[2021-04-15 01:12:30  INFO]  ["git", "show", "--no-patch", "--format=%H", "refs/temp/f3644ddd430ccc0868f634bcd5dc4a0affaac49a"]
[2021-04-15 01:12:30  INFO]  ["git", "diff", "--name-only", "f3644ddd430ccc0868f634bcd5dc4a0affaac49a"]
Files changed:
  .github/blunderbuss.yml
No gem directories changed.
NoMethodError: undefined method `each' for #<#<Class:0x00007faa1fa13c10>:0x00007faa1f983070>
     18: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/bin/toys:23:in `<main>'
     17: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/bin/toys:23:in `load'
     16: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-0.11.5/bin/toys:11:in `<top (required)>'
     15: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:426:in `run'
     14: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/errors.rb:70:in `capture_path'
     13: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:434:in `block in run'
     12: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:466:in `run_tool'
     11: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:490:in `execute_tool_in_context'
     10: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:490:in `catch'
      9: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:491:in `block in execute_tool_in_context'
      8: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:522:in `block in make_executor'
      7: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/standard_middleware/show_help.rb:234:in `run'
      6: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:522:in `block in make_executor'
      5: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/standard_middleware/show_root_version.rb:67:in `run'
      4: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:522:in `block in make_executor'
      3: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/standard_middleware/handle_usage_errors.rb:39:in `run'
      2: /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0/gems/toys-core-0.11.5/lib/toys/cli.rb:480:in `block in execute_tool_in_context'
      1: /Users/runner/work/google-cloud-ruby/google-cloud-ruby/.toys/ci.rb:48:in `run'
Error during tool execution!
    NoMethodError: undefined method `each' for #<#<Class:0x00007faa1fa13c10>:0x00007faa1f983070>

    in config file: /Users/runner/work/google-cloud-ruby/google-cloud-ruby/.toys/ci.rb:48
    while executing tool: "ci"
    with arguments: ["-v", "--only", "--test", "--github-event-name=pull_request", "--github-event-payload=/Users/runner/work/_temp/_github_workflow/event.json"]
```

**Comment by dazuma** [comment]
This should have been fixed as part of #11145 (see https://github.com/googleapis/google-cloud-ruby/pull/11145/files#diff-2e255f39c6486eda1a596e4dc1a8d5c21dd7e980eec2fbae225985fbcef1825c)

**Comment by dazuma** [comment]
If it's happening in existing PRs where the last CI run took place before #11145 was merged, you can "bounce" the CI run and force it to rerun against the latest master branch by closing and reopening the PR.

**Comment by quartzmo** [comment]
@dazuma Got it, thank you!
