### ISSUE TITLE
undefined method `name' for #<Google::Cloud::Trace::TraceRecord>

### ISSUE THREAD

**Issue by mhatch-sc** [googleapis/google-cloud-ruby#11691]
The [call_with_trace](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-trace/lib/google/cloud/trace/patches/call_with_trace.rb#L68-L71) method has a flaw in its logic. 
`span = Google::Cloud::Trace.get` Is expected to return a [Span](https://www.rubydoc.info/gems/google-cloud-trace/0.23.2/Google/Cloud/Trace/Span), but the docs for `Google::Cloud::Trace.get` specify that it could return a `Span` or a [TraceRecord](https://www.rubydoc.info/gems/google-cloud-trace/0.23.2/Google/Cloud/Trace/TraceRecord). Either way, the method expects there to be a `name` method, but only `Span` has a `name` attribute; `TraceRecord` does not. This results in the following error:

```
"undefined method `name' for #<Google::Cloud::Trace::TraceRecord:0x00005649ab7649e0> (NoMethodError)
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/google-cloud-trace-0.41.0/lib/google/cloud/trace/patches/call_with_trace.rb:71:in `run_batch'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:254:in `remote_read'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:222:in `read_unary_request'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:51:in `handle_request_response'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:122:in `run_server_method'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:460:in `block in loop_handle_server_calls'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:138:in `block in loop_execute_jobs'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:135:in `loop'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:135:in `loop_execute_jobs'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:84:in `block (2 levels) in start'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:83:in `catch'
/usr/lib/empire-grpc/vendor/bundle/ruby/2.7.0/gems/grpc-1.28.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:83:in `block in start'"
```

Note: "empire-grpc" is just the name of our application.

#### Environment details

  - OS:
  - Ruby version: 2.7
  - Gem name and version: google-cloud-tracev0.41.0

**Comment by dazuma** [comment]
Thanks for the report! Will get that fixed asap.
