### ISSUE TITLE
Document AI: Error: "Received message larger than max"

### ISSUE THREAD

**Issue by jahseng-lee** [googleapis/google-cloud-ruby#13138]
## Context

We implemented an integration with Google Document AI for parsing receipts (tax invoices specifically) a few months back.
All local + staging testing was pretty good, no big issues and the integration seemingly worked pretty well.

However, after deploying to production we started, and continue, getting high volumes of errors. Specifically, one error:
```
Error: /usr/local/bundle/gems/google-cloud-document_ai-v1beta3-0.6.0/lib/google/cloud/document_ai/v1beta3/document_processor_service/client.rb:264:in `rescue in process_document': 8:Received message larger than max (20272402 vs. 4194304). debug_error_string:{"created":"@1626829008.531532433","description":"Received message larger than max (20272402 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":206,"grpc_status":8} (Google::Cloud::ResourceExhaustedError)
```

After doing a lot of digging, I found a couple of friends which recommended configuring the `channel_args` to be unlimited, however to no avail.
I can't see **why** my client configuration doesn't work.

Our implementation:
```
      ::Google::Cloud::DocumentAI.configure do |config|
        config.credentials = @credentials_file.path
        config.channel_args = {
          "grpc.max_send_message_length"    => -1,
          "grpc.max_receive_message_length" => -1
        }
      end
      client = ::Google::Cloud::DocumentAI.document_processor_service
```
This runs in a background job FWIW. It should be noted that our configuration works (i.e. there's no other major errors whether or not we include the `channel_args`)

I can see in `google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/client.rb:88`:
```ruby
              yield @configure if block_given?
              @configure
```

and a little bit further down:
```ruby
              config_attr(:channel_args,  { "grpc.service_config_disable_resolution" => 1 }, ::Hash, nil)
```
which looks compatible with out configuration, however is doesn't seem to have resolved this issue.

When I run tests locally, the error I get is:
```ruby
Key :channel_args has not been added. Setting anyway.
```

Which seems odd, given the snippets of code I quoted above.

What am I missing?

### Current behaviour:
~55% of all images submitted in our platform are coming back as the error specified above (~1500/2700).

### Desired behaviour:
We no longer see the above error in our platform.

### Details
Versioning:

```ruby
# Google package versions:
Gemfile.lock:    google-cloud-core (1.6.0)
Gemfile.lock:      google-cloud-env (~> 1.0)
Gemfile.lock:      google-cloud-errors (~> 1.0)
Gemfile.lock:    google-cloud-document_ai (1.0.2)
Gemfile.lock:      google-cloud-core (~> 1.6)
Gemfile.lock:      google-cloud-document_ai-v1 (>= 0.0, < 2.a)
Gemfile.lock:      google-cloud-document_ai-v1beta3 (>= 0.0, < 2.a)
Gemfile.lock:    google-cloud-document_ai-v1 (0.2.1)
Gemfile.lock:      google-cloud-errors (~> 1.0)
Gemfile.lock:    google-cloud-document_ai-v1beta3 (0.9.0)
Gemfile.lock:      google-cloud-errors (~> 1.0)
Gemfile.lock:    google-cloud-env (1.5.0)
Gemfile.lock:    google-cloud-errors (1.1.0)
Gemfile.lock:  google-cloud-document_ai

# Ruby versioning:
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

$ rails -v
Rails 6.1.4
```

**Comment by dazuma** [comment]
Try this:

```ruby
client = ::Google::Cloud::DocumentAI.document_processor_service do |config|
  config.credentials = @credentials_file.path
  config.channel_args = {
    "grpc.max_send_message_length" => -1,
    "grpc.max_receive_message_length" => -1,
    "grpc.service_config_disable_resolution" => 1
  }
end
```

(The `channel_args` key isn't part of the configuration at the `::Google::Cloud::DocumentAI` level, and it may not be setting properly at that level, as suggested by the error message you mentioned.)

Additionally, I suggest updating google-cloud-document_ai to `~> 1.0` so it defaults to the non-beta `v1` version of the service.

**Comment by jahseng-lee** [comment]
@dazuma Thanks for the udpate.

I'll give it a shot and report back with the results.

**Comment by jahseng-lee** [comment]
Small update:

Had to use the `beta3` version specifically as we're using the `Receipt Parser` processor which isn't supported by the v1 document-ai package at the moment.

Got that working in staging environment but still need to deploy to production before we can know if the fix worked. Will update this thread as soon as we know 🙂

**Comment by jahseng-lee** [comment]
Hi @dazuma, this seems to be fixed for us!

Thanks so much for your help 🙂

**Comment by dimroc** [comment]
Hi all, just a heads up that this still occurs for me with document-ai-v1 with online processing of documents with `client.process_document`. I was able to get around it using a piece of @dazuma's snippet.

```
2023-05-21T21:34:13.279Z 56793 TID-1ym8 DocumentAiJob JID-18b79e22ca7af6a2d2e47170 INFO: fail: 5.057 sec
2023-05-21T21:34:13.279Z 56793 TID-1ym8 WARN: {"context":"Job raised exception","job":{"jid":"18b79e22ca7af6a2d2e47170","queue":"default","jobtype":"DocumentAiJob","args":["852zga6107771syw2499yqhljoan"],"created_at":"2023-05-21T21:17:10.799368Z","enqueued_at":"2023-05-21T21:33:43.554349Z","retry":25,"failure":{"retry_count":6,"remaining":19,"failed_at":"2023-05-21T21:17:16.125038Z","next_at":"2023-05-21T21:51:14.05877Z","message":"8:Received message larger than max (5510191 vs. 4194304). debug_error_string:{UNKNOWN:Error received from peer documentai.googleapis.com {grpc_message:\"Received message larger than max (5510191 vs. 4194304)\", grpc_status:8, created_time:\"2023-05-21T14:28:48.056008-07:00\"}}","errtype":"Google::Cloud::ResourceExhaustedError","backtrace":["/Users/dimroc/.gem/ruby/3.2.2/gems/google-cloud-document_ai-v1-0.11.0/lib/google/cloud/document_ai/v1/document_processor_service/client.rb:294:in `rescue in process_document'","/Users/dimroc/.gem/ruby/3.2.2/gems/google-cloud-document_ai-v1-0.11.0/lib/google/cloud/document_ai/v1/document_processor_service/client.rb:256:in `process_document'","/Users/dimroc/workspace/ponds/rails/app/services/document_ai_helper.rb:25:in `process_document_online'","/Users/dimroc/workspace/ponds/rails/app/jobs/document_ai_job.rb:31:in `block in document_ai_online_processing'","/Users/dimroc/.gem/ruby/3.2.2/gems/activestorage-7.0.4.3/lib/active_storage/downloader.rb:15:in `block in open'","/Users/dimroc/.gem/ruby/3.2.2/gems/activestorage-7.0.4.3/lib/active_storage/downloader.rb:24:in `open_tempfile'","/Users/dimroc/.gem/ruby/3.2.2/gems/activestorage-7.0.4.3/lib/active_storage/downloader.rb:12:in `open'","/Users/dimroc/.gem/ruby/3.2.2/gems/activestorage-7.0.4.3/lib/active_storage/service.rb:90:in `open'","/Users/dimroc/.gem/ruby/3.2.2/gems/activestorage-7.0.4.3/app/models/active_storage/blob.rb:301:in `open'","/Users/dimroc/workspace/ponds/rails/app/jobs/document_ai_job.rb:28:in `document_ai_online_processing'","/Users/dimroc/workspace/ponds/rails/app/jobs/document_ai_job.rb:16:in `perform'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:146:in `block (2 levels) in process'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/middleware/chain.rb:129:in `block in invoke'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/middleware/batch.rb:21:in `call'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/middleware/chain.rb:131:in `block in invoke'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/middleware/chain.rb:134:in `invoke'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:145:in `block in process'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:135:in `block (3 levels) in dispatch'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/rails.rb:50:in `block in call'","/Users/dimroc/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'","/Users/dimroc/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:72:in `block in wrap'","/Users/dimroc/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'","/Users/dimroc/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:71:in `wrap'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/rails.rb:49:in `call'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:130:in `block (2 levels) in dispatch'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/job_logger.rb:6:in `call'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:125:in `block in dispatch'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/logging.rb:43:in `with_context'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/logging.rb:37:in `with_job_hash_context'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:124:in `dispatch'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:144:in `process'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:88:in `process_one'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/processor.rb:71:in `run'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/util.rb:17:in `watchdog'","/Users/dimroc/.gem/ruby/3.2.2/gems/faktory_worker_ruby-1.3.0/lib/faktory/util.rb:26:in `block in safe_thread'"]}}}
2023-05-21T21:34:13.279Z 56793 TID-1ym8 WARN: Google::Cloud::ResourceExhaustedError: 8:Received message larger than max (5510191 vs. 4194304). debug_error_string:{UNKNOWN:Error received from peer documentai.googleapis.com {grpc_message:"Received message larger than max (5510191 vs. 4194304)", grpc_status:8, created_time:"2023-05-21T14:34:13.276815-07:00"}}
2023-05-21T21:34:13.279Z 56793 TID-1ym8 WARN: /Users/dimroc/.gem/ruby/3.2.2/gems/google-cloud-document_ai-v1-0.11.0/lib/google/cloud/document_ai/v1/document_processor_service/client.rb:294:in `rescue in process_document'
/Users/dimroc/.gem/ruby/3.2.2/gems/google-cloud-document_ai-v1-0.11.0/lib/google/cloud/document_ai/v1/document_processor_service/client.rb:256:in `process_document'
/Users/dimroc/workspace/ponds/rails/app/services/document_ai_helper.rb:26:in `process_document_online'
```
