### ISSUE TITLE
[Test failures] google-cloud-bigquery acceptance tests (consistent)

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#13298]
These errors and failures have been occasionally recurring for some time now. 

[Example log](https://source.cloud.google.com/results/invocations/cc189fb8-22d2-4edb-bf70-560f93c02cc1/log)

#### Log output

```sh
# Running:

.................................S..Retrying Google::Cloud::Bigquery::Table::bigquery#test_0024_imports data from a file in your bucket with load_job (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0024_imports data from a file in your bucket with load_job (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0024_imports data from a file in your bucket with load_job (3)
FRetrying Google::Cloud::Bigquery::Table::bigquery#test_0010_writes the schema of a table to a File (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0010_writes the schema of a table to a File (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0010_writes the schema of a table to a File (3)
FRetrying Google::Cloud::Bigquery::Table::bigquery#test_0035_extracts data to a file in your bucket with extract_job (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0035_extracts data to a file in your bucket with extract_job (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0035_extracts data to a file in your bucket with extract_job (3)
F...Retrying Google::Cloud::Bigquery::Table::bigquery#test_0036_extracts data to a url in your bucket with extract (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0036_extracts data to a url in your bucket with extract (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0036_extracts data to a url in your bucket with extract (3)
ERetrying Google::Cloud::Bigquery::Table::bigquery#test_0001_has the attributes of a table (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0001_has the attributes of a table (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0001_has the attributes of a table (3)
FRetrying Google::Cloud::Bigquery::Table::bigquery#test_0018_inserts rows directly and gets its data (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0018_inserts rows directly and gets its data (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0018_inserts rows directly and gets its data (3)
F.Retrying Google::Cloud::Bigquery::Table::bigquery#test_0026_imports data from a local file with load (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0026_imports data from a local file with load (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0026_imports data from a local file with load (3)
E.Retrying Google::Cloud::Bigquery::Table::bigquery#test_0011_writes the schema of a table to a filename (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0011_writes the schema of a table to a filename (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0011_writes the schema of a table to a filename (3)
FRetrying Google::Cloud::Bigquery::Table::bigquery#test_0037_extracts data to a file in your bucket with extract (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0037_extracts data to a file in your bucket with extract (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0037_extracts data to a file in your bucket with extract (3)
E......Retrying Google::Cloud::Bigquery::Table::bigquery#test_0022_inserts rows asynchronously with insert_ids option (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0022_inserts rows asynchronously with insert_ids option (2)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0022_inserts rows asynchronously with insert_ids option (3)
FRetrying Google::Cloud::Bigquery::Table::bigquery#test_0020_inserts rows with insert_ids option (1)
Retrying Google::Cloud::Bigquery::Table::bigquery#test_0020_inserts rows with insert_ids option (2)
......................................................................................................Retrying Google::Cloud::Bigquery::advanced::bigquery#test_0002_queries values in standard mode (1)
...........................................................................................

Finished in 1027.114153s, 0.2434 runs/s, 4.4036 assertions/s.

  1) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0024_imports data from a file in your bucket with load_job [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:777]:
Expected #<Google::Cloud::Bigquery::LoadJob:0x000056466e791250 @service=Google::Cloud::Bigquery::Service(helical-zone-771), @gapi=#<Google::Apis::BigqueryV2::Job:0x000056466e8aada8 @configuration=#<Google::Apis::BigqueryV2::JobConfiguration:0x000056466e89b268 @job_type="LOAD", @load=#<Google::Apis::BigqueryV2::JobConfigurationLoad:0x000056466e883cd0 @destination_table=#<Google::Apis::BigqueryV2::TableReference:0x000056466e8506a0 @dataset_id="gcloud_ruby_acceptance_2021_08_04t18_21_53z_0504f213_dataset", @project_id="helical-zone-771", @table_id="kittens">, @source_format="NEWLINE_DELIMITED_JSON", @schema=#<Google::Apis::BigqueryV2::TableSchema:0x000056466e8212d8 @fields=[#<Google::Apis::BigqueryV2::TableFieldSchema:0x000056466e812530 @name="id", @type="INTEGER", @mode="REQUIRED", @description="id description">]>, @source_uris=["gs://gcloud_ruby_acceptance_2021_08_04t18_21_53z_0504f213_bucket/kitten-test-data-4142d55bf2f00e4274584727b159f1ec.json"]>>, @job_reference=#<Google::Apis::BigqueryV2::JobReference:0x000056466e9686a0 @job_id="job_sMCn3BkzcaK9pFtfzm3ZDJ-8RH6u", @project_id="helical-zone-771", @location="US">, @etag="GsF9djH6a968SF5vXUDq/Q==", @id="helical-zone-771:US.job_sMCn3BkzcaK9pFtfzm3ZDJ-8RH6u", @kind="bigquery#job", @self_link="https://bigquery.googleapis.com/bigquery/v2/projects/helical-zone-771/jobs/job_sMCn3BkzcaK9pFtfzm3ZDJ-8RH6u?location=US", @statistics=#<Google::Apis::BigqueryV2::JobStatistics:0x000056466e953c28 @creation_time=1628101566254, @start_time=1628101566393, @end_time=1628101567077, @total_slot_ms=144, @reservation_id="default-pipeline">, @status=#<Google::Apis::BigqueryV2::JobStatus:0x000056466e8e0f48 @state="DONE", @error_result=#<Google::Apis::BigqueryV2::ErrorProto:0x000056466e8da440 @message="Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.", @reason="invalid", @location="gs://gcloud_ruby_acceptance_2021_08_04t18_21_53z_0504f213_bucket/kitten-test-data-4142d55bf2f00e4274584727b159f1ec.json">, @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466ed4a930 @message="Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.", @reason="invalid", @location="gs://gcloud_ruby_acceptance_2021_08_04t18_21_53z_0504f213_bucket/kitten-test-data-4142d55bf2f00e4274584727b159f1ec.json">, #<Google::Apis::BigqueryV2::ErrorProto:0x000056466ed48928 @message="Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0", @reason="invalid">, #<Google::Apis::BigqueryV2::ErrorProto:0x000056466ed42758 @message="Error while reading data, error message: JSON parsing error in row starting at position 0: No such field: name.", @reason="invalid", @location="gs://gcloud_ruby_acceptance_2021_08_04t18_21_53z_0504f213_bucket/kitten-test-data-4142d55bf2f00e4274584727b159f1ec.json">]>, @user_email="kokoro@helical-zone-771.iam.gserviceaccount.com">> to not be failed?.

  2) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0010_writes the schema of a table to a File [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:337]:
Expected: 4
  Actual: 1

  3) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0035_extracts data to a file in your bucket with extract_job [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:976]:
Expected 0 to be > 0.

  4) Error:
Google::Cloud::Bigquery::Table::bigquery#test_0036_extracts data to a url in your bucket with extract:
Google::Cloud::InvalidArgumentError: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2786:in `rescue in ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2781:in `ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2354:in `load'
    /workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:982:in `block (2 levels) in <top (required)>'

  5) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0001_has the attributes of a table [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:135]:
Expected [:id] to include :breed.

  6) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0018_inserts rows directly and gets its data [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:517]:
Expected #<Google::Cloud::Bigquery::InsertResponse:0x000056466f0613d0 @rows=[{:name=>"silvano", :breed=>"the cat kind", :id=>4, :dob=>2021-08-04 18:27:18.606497109 UTC}, {:name=>"ryan", :breed=>"golden retriever?", :id=>5, :dob=>2021-08-04 18:27:18.606500287 UTC}, {:name=>"stephen", :breed=>"idkanycatbreeds", :id=>6, :dob=>2021-08-04 18:27:18.606501129 UTC}], @gapi=#<Google::Apis::BigqueryV2::InsertAllTableDataResponse:0x000056466f07ad30 @kind="bigquery#tableDataInsertAllResponse", @insert_errors=[#<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466f0794a8 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466f0785d0 @message="no such field: dob.", @reason="invalid", @location="dob", @debug_info="">], @index=0>, #<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466f071668 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466f070ab0 @message="no such field: name.", @reason="invalid", @location="name", @debug_info="">], @index=1>, #<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466f069530 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466f0689f0 @message="no such field: dob.", @reason="invalid", @location="dob", @debug_info="">], @index=2>]>> to be success?.

  7) Error:
Google::Cloud::Bigquery::Table::bigquery#test_0026_imports data from a local file with load:
Google::Cloud::InvalidArgumentError: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2786:in `rescue in ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2781:in `ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2354:in `load'
    /workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:795:in `block (2 levels) in <top (required)>'

  8) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0011_writes the schema of a table to a filename [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:360]:
Expected: 4
  Actual: 1

  9) Error:
Google::Cloud::Bigquery::Table::bigquery#test_0037_extracts data to a file in your bucket with extract:
Google::Cloud::InvalidArgumentError: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2786:in `rescue in ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2781:in `ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:2354:in `load'
    /workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:999:in `block (2 levels) in <top (required)>'

 10) Failure:
Google::Cloud::Bigquery::Table::bigquery#test_0022_inserts rows asynchronously with insert_ids option [/workspace/google-cloud-bigquery/acceptance/bigquery/table_test.rb:729]:
Expected #<Google::Cloud::Bigquery::Table::AsyncInserter::Result:0x000056466fa00fa8 @insert_response=#<Google::Cloud::Bigquery::InsertResponse:0x000056466fa00fd0 @rows=[{:name=>"silvano", :breed=>"the cat kind", :id=>4, :dob=>2021-08-04 18:28:17.799677688 UTC}, {:name=>"ryan", :breed=>"golden retriever?", :id=>5, :dob=>2021-08-04 18:28:17.799680585 UTC}, {:name=>"stephen", :breed=>"idkanycatbreeds", :id=>6, :dob=>2021-08-04 18:28:17.799681421 UTC}], @gapi=#<Google::Apis::BigqueryV2::InsertAllTableDataResponse:0x000056466fa28a80 @kind="bigquery#tableDataInsertAllResponse", @insert_errors=[#<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466fa1f430 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466fa1e558 @message="no such field: name.", @reason="invalid", @location="name", @debug_info="">], @index=0>, #<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466fa17438 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466fa168d0 @message="no such field: dob.", @reason="invalid", @location="dob", @debug_info="">], @index=1>, #<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x000056466fa144e0 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x000056466fa03a50 @message="no such field: name.", @reason="invalid", @location="name", @debug_info="">], @index=2>]>>, @error=nil> to be success?.

250 runs, 4523 assertions, 7 failures, 3 errors, 1 skips

```

**Comment by quartzmo** [comment]
More recurring errors:

```sh
  1) Failure:
Google::Cloud::Bigquery::advanced::bigquery#test_0008_queries max scale numeric and bignumeric values [/workspace/google-cloud-bigquery/acceptance/bigquery/advanced_test.rb:218]:
Expected: 1
  Actual: 0

  2) Failure:
Google::Cloud::Bigquery::advanced::bigquery#test_0002_queries values in standard mode [/workspace/google-cloud-bigquery/acceptance/bigquery/advanced_test.rb:46]:
Expected: 1
  Actual: 0

  3) Failure:
Google::Cloud::Bigquery::advanced::bigquery#test_0003_queries repeated scalars in legacy mode [/workspace/google-cloud-bigquery/acceptance/bigquery/advanced_test.rb:56]:
Expected: 3
  Actual: 0

  4) Failure:
Google::Cloud::Bigquery::advanced::bigquery#test_0004_queries repeated records in legacy mode [/workspace/google-cloud-bigquery/acceptance/bigquery/advanced_test.rb:66]:
Expected: 3
  Actual: 0
```

**Comment by dazuma** [comment]
I also noticed this:

```
...................................................................................................................S.........Retrying Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0001_creates and populates and drops a table with ddl/dml query jobs (1)
Retrying Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0001_creates and populates and drops a table with ddl/dml query jobs (2)
.Retrying Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0002_creates and populates and drops a table with ddl/dml queries (1)
Retrying Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0002_creates and populates and drops a table with ddl/dml queries (2)
Retrying Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0002_creates and populates and drops a table with ddl/dml queries (3)
E...........................................................................................................................

Finished in 1037.020679s, 0.2411 runs/s, 4.4869 assertions/s.

  1) Error:
Google::Cloud::Bigquery::Dataset::ddl_dml::bigquery#test_0002_creates and populates and drops a table with ddl/dml queries:
Google::Cloud::PermissionDeniedError: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb:2689:in `rescue in ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb:2684:in `ensure_job_succeeded!'
    /workspace/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb:1707:in `query'
    /workspace/google-cloud-bigquery/acceptance/bigquery/dataset_ddl_dml_test.rb:146:in `block (2 levels) in <top (required)>'
```

In this case the rate limit error might be covering up the actual error, as it looks like this call might have retried 3+ times.

**Comment by dazuma** [comment]
Still happening. There may be a variety of issues that need addressing. See logs from recent nightly runs.
