### ISSUE TITLE
test(pubsub): Samples acceptance test failure

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#13691]
The google-cloud-pubsub samples acceptance tests are consistently failing.

#### Environment details

Both local dev and in Kokoro, using the Ruby CI project.

#### Full backtrace

```sh
# Running:

.......................F....

Finished in 979.930681s, 0.0286 runs/s, 0.1806 assertions/s.

  1) Failure:
schemas#test_0001_supports pubsub_create_schema, pubsub_get_schema, pubsub_list_schemas, pubsub_delete_schema:
Expected #<Google::Cloud::PubSub::Schema:0x00007fc9fd1634a0 @grpc=<Google::Cloud::PubSub::V1::Schema: name: "projects/helical-zone-771/schemas/ruby-pubsub-samples-test-schema-4bde54c2", type: :AVRO, definition: "{
  "type":"record",
  "name":"State",
  "namespace":"utilities",
  "doc":"A list of states in the United States of America.",
  "fields":[
    {
      "name":"name",
      "type":"string",
      "doc":"The common name of the state."
    },
    {
      "name":"post_abbr",
      "type":"string",
      "doc":"The postal code abbreviation of the state."
    }
  ]
}">, @service=#<Google::Cloud::PubSub::Service (helical-zone-771)>, @exists=nil, @view=:FULL> to not be truthy.

Error:
schemas#test_0001_supports pubsub_create_schema, pubsub_get_schema, pubsub_list_schemas, pubsub_delete_schema:
Google::Cloud::InternalError: 13:A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]. debug_error_string:{"created":"@1629834798.865898000","description":"Error received from peer ipv4:142.250.68.10:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]","grpc_status":13}
    /Users/quartzmo/.rbenv/versions/3.0.1/gemsets/quartzmo/gems/google-cloud-pubsub-v1-0.6.0/lib/google/cloud/pubsub/v1/schema_service/client.rb:447:in `rescue in delete_schema'
    /Users/quartzmo/.rbenv/versions/3.0.1/gemsets/quartzmo/gems/google-cloud-pubsub-v1-0.6.0/lib/google/cloud/pubsub/v1/schema_service/client.rb:411:in `delete_schema'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:369:in `delete_schema'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/schema.rb:132:in `delete'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-pubsub/samples/acceptance/schemas_test.rb:29:in `block (2 levels) in <top (required)>'
```

**Comment by quartzmo** [comment]
https://source.cloud.google.com/results/invocations/4d733a8b-968c-4442-9012-ff935e466ca0/log

**Comment by dazuma** [comment]
Whoa that's disturbing. Is this consistent?

**Comment by quartzmo** [comment]
I would imagine the schema delete is eventually consistent, and that the assertion just comes too soon, but I'll ask about it.

**Comment by quartzmo** [comment]
When run in isolation with `focus` the test failed with the above error only 2 out 7 times.
