### ISSUE TITLE
Bigquery: Add support for precision, scale in nested fields

### ISSUE THREAD

**Issue by inz** [googleapis/google-cloud-ruby#13987]
#13102 added support for parameterized types to BigQuery schemas, but `Google::Cloud::Bigquery::Schema::Field#add_field` does not yet support the `precision` and `scale` arguments (only `Google::Cloud::Bigquery::Schema#add_field` does).

#### Steps to reproduce

  1. Create a table with a schema that includes nested numeric/bignumeric fields

#### Code example

Failing test (numeric field `my_numeric` added to `Google::Cloud::Bigquery::Table::mock_bigquery#test_0008_allows nested records several levels deep`, see https://github.com/inz/google-cloud-ruby/commit/d45659e615a9c95d27c859265fbc17cf2b5cf044):

```ruby
  it "allows nested records several levels deep" do
    mock = Minitest::Mock.new
    nested_schema_hash = {
      fields: [
        { name: "first_name", type: "STRING", mode: "REQUIRED", description: nil, fields: [] },
        { name: "countries_lived", type: "RECORD", mode: "REPEATED", description: nil, fields: [
            { name: "cities_lived", type: "RECORD", mode: "REPEATED", description: nil, fields: [
                { mode: "NULLABLE", name: "rank", type: "INTEGER", description: "An integer value from 1 to 100", fields: [] },
                { mode: "NULLABLE", name: "my_numeric", type: "NUMERIC", description: "A numeric value", fields: [], precision: precision_numeric, scale: scale_numeric }
              ]
            }
          ]
        }
      ]
    }
    nested_schema_gapi = Google::Apis::BigqueryV2::TableSchema.from_json nested_schema_hash.to_json
    returned_table_gapi = table_gapi.dup
    returned_table_gapi.schema = nested_schema_gapi
    patch_table_gapi = Google::Apis::BigqueryV2::Table.new schema: nested_schema_gapi, etag: etag
    mock.expect :patch_table, returned_table_gapi,
      [table.project_id, table.dataset_id, table.table_id, patch_table_gapi, {options: {header: {"If-Match" => etag}}}]
    mock.expect :get_table, returned_table_gapi, [table.project_id, table.dataset_id, table.table_id]
    table.service.mocked_service = mock

    table.schema replace: true do |schema|
      schema.string "first_name", mode: :required
      schema.record "countries_lived", mode: :repeated do |nested|
        nested.record "cities_lived", mode: :repeated do |nested_2|
          nested_2.integer "rank", description: "An integer value from 1 to 100"
          nested_2.numeric "my_numeric", description: "A numeric value", precision: precision_numeric, scale: scale_numeric
        end
      end
    end

    mock.verify
  end
```

#### Full backtrace

```sh
Google::Cloud::Bigquery::Table::mock_bigquery#test_0008_allows nested records several levels deep:
ArgumentError: unknown keywords: precision, scale
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb:942:in `add_field'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb:614:in `numeric'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb:382:in `block (5 levels) in <top (required)>'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb:894:in `record'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb:380:in `block (4 levels) in <top (required)>'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb:630:in `record'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb:379:in `block (3 levels) in <top (required)>'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/table.rb:999:in `schema'
    /Users/inz/Projects/google-cloud-ruby/google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb:377:in `block (2 levels) in <top (required)>'
```

**Comment by quartzmo** [comment]
@inz Thank you for reporting this issue! I'll try to fix it today.

**Comment by inz** [comment]
👍 Thanks for the quick fix!
