### ISSUE TITLE
bug: owlbot create PRs failure

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-cloud-ruby#13983]
```Already have image (with digest): gcr.io/cloud-devrel-public-resources/owlbot-ruby:latest@sha256:400120ae10b751bcfac14f1a0528b5e7d6a3bd1cbdf49b786d6394b698e966b0
<internal:dir>:15:in `open': No such file or directory @ dir_initialize - /workspace/google-cloud-ruby/owl-bot-staging (Errno::ENOENT)
	from /ruby-postprocessor/owlbot.rb:239:in `children'
	from /ruby-postprocessor/owlbot.rb:239:in `setup'
	from /ruby-postprocessor/owlbot.rb:224:in `entrypoint'
	from /ruby-postprocessor/entrypoint.rb:19:in `<main>'
```

https://pantheon.corp.google.com/cloud-build/builds;region=global/0b97a5e1-8888-4f4a-af88-dcfc92ee0222?project=repo-automation-bots

**Comment by dazuma** [comment]
@sofisl Was this a one-time failure of the 9/13 run, or is it happening repeatedly?
