### ISSUE TITLE
Logging a BigDecimal within a hash raises a Google::Protobuf::TypeError 

### ISSUE THREAD

**Issue by conleysionic** [googleapis/google-cloud-ruby#15695]
Hello, I've been attempting to log some Active Record queries that involve Decimal data types, so `BigDecimal` within Ruby, and it raises an error.  I see BigDecimal-related code and tests in the repo, so I figured this may be a regression.  

#### Environment details

  - OS: Docker image based on `circleci/ruby:2.6.6`, running within a Cloud Run service.   Also reproducible on my local machine, which is macOS 11.1 
  - Ruby version: 2.6.6
  - Gem name and version: `google-cloud-logging` 2.2.1 ; Below is a section of my `Gemfile.lock` with other Google gem versions that may be relevant: 

```
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.2.0)
    google-cloud-logging (2.2.1)
      concurrent-ruby (~> 1.1)
      google-cloud-core (~> 1.5)
      google-cloud-logging-v2 (~> 0.0)
      stackdriver-core (~> 1.3)
    google-cloud-logging-v2 (0.5.4)
      gapic-common (>= 0.7, < 2.a)
      google-cloud-errors (~> 1.0)
    google-protobuf (3.18.1)
    googleapis-common-protos (1.3.12)
      google-protobuf (~> 3.14)
      googleapis-common-protos-types (~> 1.2)
      grpc (~> 1.27)
    googleapis-common-protos-types (1.2.0)
      google-protobuf (~> 3.14)
    googleauth (1.0.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    grpc (1.41.0)
      google-protobuf (~> 3.17)
      googleapis-common-protos-types (~> 1.0)
```

#### Steps to reproduce

 - Initialize a `Logger` (I created a `Google::Cloud::Logging.new`, then invoked `.resource` on that object, then invoked `.logger` on that object with the previously created resource) 
 - Attempt to use structured logging with a BigDecimal, such as with the code sample below

#### Code example

`logger.info ({ decimal: BigDecimal("0.2") })` is enough to produce the error. 

#### Backtrace

```
/approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:45:in `initialize': Expected number type for double field 'number_value' (given BigDecimal). (Google::Protobuf::TypeError)
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:45:in `new'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:45:in `object_to_value'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:27:in `block in hash_to_struct'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:27:in `each'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:27:in `map'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/convert.rb:27:in `hash_to_struct'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/entry.rb:507:in `append_payload'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/entry.rb:442:in `to_grpc'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:508:in `addl_bytes_for'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:479:in `try_add'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:146:in `block (2 levels) in write_entries'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:136:in `each'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:136:in `block in write_entries'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/async_writer.rb:133:in `write_entries'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/logger.rb:550:in `write_entry'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/logger.rb:319:in `add'
	from /approot/vendor/bundle/ruby/2.6.0/gems/google-cloud-logging-2.2.1/lib/google/cloud/logging/logger.rb:219:in `info'
```

The rest of the trace is server and application code, irrelevant to this bug, as it is reproducible in REPL without that context. As mentioned above, using structured logging in a freshly-instantiated `Logger` with no other context is enough to reproduce this error.  

## Possible Solutions

The error is thrown [here](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-logging/lib/google/cloud/logging/convert.rb#L45), presumably because `BigDecimal` is `Numeric` but not an acceptable number value for protobuf.  I imagine adding BigDecimal case to that switch would be enough to solve the problem, converting it to a float or string instead.  I may submit a pull request to that effect at some point, though I'm not sure if it should be a float or a string.  I would imagine a float would be more useful as it would be comparable in the logging query language.  Feedback would be appreciated. 

```
        def self.object_to_value obj
          case obj
          when NilClass
            Google::Protobuf::Value.new null_value: :NULL_VALUE
          when Numeric
            Google::Protobuf::Value.new number_value: obj
```

**Comment by dazuma** [comment]
Apologies that this fell through the cracks. The logging library is badly out of date; we have a project to reevaluate and redesign it, and we'll make sure this gets addressed in the process. We'll be tracking this internally at Google for now, so I'm closing this issue from GitHub. If you have additional questions or comments feel free to reopen (or open a new issue), and reference internal project number b/407801439.
