### ISSUE TITLE
google-cloud-logging: Google::Cloud::Logging::Project#resource_descriptors does not work

### ISSUE THREAD

**Issue by knu** [googleapis/google-cloud-ruby#18231]
#### Environment details

  - OS: macOS 12.3.1
  - Ruby version: 2.7.5
  - Gem name and version: google-cloud-logging-2.2.2

#### Steps to reproduce

  1. Just call resource_descriptors on a logging object (instance of Google::Cloud::Logging::Project) as documented [here](https://cloud.google.com/ruby/docs/reference/google-cloud-logging/latest/Google-Cloud-Logging-ResourceDescriptor-List).

#### Code example

```ruby
logging = Google::Cloud::Logging.new(project_id: ENV.fetch('GOOGLE_CLOUD_LOGGING_PROJECT_ID'), credentials: Google::Cloud::Logging::Credentials.new(JSON.parse(ENV.fetch('GOOGLE_CLOUD_LOGGING_CREDENTIALS_JSON'))))
logging.resource_descriptors
```

#### Full backtrace

```
Traceback (most recent call last):
        21: from .../bin/irb:23:in `<main>'
        20: from .../bin/irb:23:in `load'
        19: from .../exe/irb:11:in `<top (required)>'
         2: from (irb):2:in `<main>'
         1: from .../gems/2.7.0/gems/google-cloud-logging-2.2.2/lib/google/cloud/logging/project.rb:551:in `resource_descriptors'
.../gems/2.7.0/gems/google-cloud-logging-2.2.2/lib/google/cloud/logging/resource_descriptor/list.rb:154:in `from_grpc': undefined method `resource_descriptors' for #<Gapic::PagedEnumerable:0x00007f933ad5b270> (NoMethodError)
```

**Comment by NivedhaSenthil** [comment]
@knu Thanks for reporting, I am able reproduce the issue too. We will try fixing this sooner 👍
