### ISSUE TITLE
[Test failures] google-cloud-asset sample tests (consistent)

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#18360]
```
Asset Quickstart::batch_get_history#test_0001_puts asset history:
Google::Cloud::InvalidArgumentError: 3:The following 1 resources don't exist in projects/542339357638 : //storage.googleapis.com/ruby_asset_sample_262707acb2e6ed964ad2d3523a6c81aa. debug_error_string:{"created":"@1654675349.668435806","description":"Error received from peer ipv4:74.125.135.95:443","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"The following 1 resources don't exist in projects/542339357638 : //storage.googleapis.com/ruby_asset_sample_262707acb2e6ed964ad2d3523a6c81aa","grpc_status":3}
    /workspace/google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb:634:in `rescue in batch_get_assets_history'
    /workspace/google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb:596:in `batch_get_assets_history'
    /workspace/google-cloud-asset/samples/quickstart.rb:62:in `batch_get_history'
    /workspace/google-cloud-asset/samples/acceptance/quickstart_test.rb:78:in `block (4 levels) in <top (required)>'
```

Seems to be pretty consistent.

**Comment by dazuma** [comment]
This is still happening. From the 2022-08-04 nightly run:

```
1) Error:
Asset Quickstart::batch_get_history#test_0001_puts asset history:
Google::Cloud::InvalidArgumentError: 3:The following 1 resources don't exist in projects/542339357638 : //[storage.googleapis.com/ruby_asset_sample_979fe3fd8edb0e4c31a88039cbc9e16a](https://www.google.com/url?q=http://storage.googleapis.com/ruby_asset_sample_979fe3fd8edb0e4c31a88039cbc9e16a&sa=D). debug_error_string:{UNKNOWN:Error received from peer ipv4:74.125.142.95:443 {created_time:"2022-08-04T08:09:32.102430035+00:00", grpc_status:3, grpc_message:"The following 1 resources don\'t exist in projects/542339357638 : //[storage.googleapis.com/ruby_asset_sample_979fe3fd8edb0e4c31a88039cbc9e16a](https://www.google.com/url?q=http://storage.googleapis.com/ruby_asset_sample_979fe3fd8edb0e4c31a88039cbc9e16a&sa=D)"}}
    /[h/.gem/gems/google-cloud-asset-v1-0.20.0/lib/google/cloud/asset/v1/asset_service/client.rb:634](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-asset-v1-0.20.0/lib/google/cloud/asset/v1/asset_service/client.rb?l=634):in `rescue in batch_get_assets_history'
    /[h/.gem/gems/google-cloud-asset-v1-0.20.0/lib/google/cloud/asset/v1/asset_service/client.rb:596](https://cs.corp.google.com/piper///depot/google3/h/.gem/gems/google-cloud-asset-v1-0.20.0/lib/google/cloud/asset/v1/asset_service/client.rb?l=596):in `batch_get_assets_history'
    /[workspace/google-cloud-asset/samples/quickstart.rb:62](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-asset/samples/quickstart.rb?l=62):in `batch_get_history'
    /[workspace/google-cloud-asset/samples/acceptance/quickstart_test.rb:78](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-asset/samples/acceptance/quickstart_test.rb?l=78):in `block (4 levels) in <top (required)>'
```
