### ISSUE TITLE
[Test failures] google-cloud-datastore-admin-v1 samples test (consistent)

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#18361]
```
Firestore in Datastore mode Admin V1 samples#test_0003_entities_export, entities_import:
NoMethodError: undefined method `files' for nil:NilClass

    files = storage.bucket(storage_bucket_name).files prefix: storage_file_prefix
                                               ^^^^^^
    /workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb:65:in `ensure in block (2 levels) in <top (required)>'
    /workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb:66:in `block (2 levels) in <top (required)>'
```

Might be a missing fixture.

**Comment by dazuma** [comment]
This is still happening. From the 2022-08-04 nightly run:

```
1) Error:
Firestore in Datastore mode Admin V1 samples#test_0003_entities_export, entities_import:
NoMethodError: undefined method `files' for nil:NilClass

    files = storage.bucket(storage_bucket_name).files prefix: storage_file_prefix
                                               ^^^^^^
    /[workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb:65](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb?l=65):in `ensure in block (2 levels) in <top (required)>'
    /[workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb:66](https://cs.corp.google.com/piper///depot/google3/workspace/google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb?l=66):in `block (2 levels) in <top (required)>'
```
