### ISSUE TITLE
[BigQuery] Parameter conversion fails for arrays of structs

### ISSUE THREAD

**Issue by matthieuprat** [googleapis/google-cloud-ruby#18399]
The BigQuery client fails to convert arrays of structs as shown in the example below.

#### Environment details

  - OS: macOS
  - Ruby version: 3.1.2
  - Gem name and version: google-cloud-bigquery@1.38.1

#### Code example

```ruby
bigquery = Google::Cloud::Bigquery.new
bigquery.query "SELECT @value AS value",
               params: { value: [{ foo: 1 }] },
               types:  { value: [{ foo: :INT64 }] }
```

Expected this to return `[{ value: [{ foo: 1 }] }]` but an `ArgumentError` is raised instead.

(Note that the issue also occurs without explicitly passing parameter types.)

#### Full backtrace

```
ArgumentError: types Array [{:foo=>:INT64}] should include only a single symbol element.
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/convert.rb:263:in `extract_array_type'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/convert.rb:239:in `to_json_value'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/convert.rb:118:in `to_query_param_value'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/convert.rb:253:in `to_query_param'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/query_job.rb:1014:in `block in set_params_and_types'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/query_job.rb:1012:in `each'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/query_job.rb:1012:in `map'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/query_job.rb:1012:in `set_params_and_types'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/query_job.rb:791:in `from_options'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/project.rb:651:in `query_job'
from google-cloud-bigquery (1.38.1) lib/google/cloud/bigquery/project.rb:919:in `query'
```

#### Additional information

The `bq` command line tool returns the expected result:

```shell
$ bq query --use_legacy_sql=false \
  --parameter='value:ARRAY<STRUCT<foo STRING>>:[{ "foo": 1 }]' \
  "SELECT @value AS value"
+---------------+
|     value     |
+---------------+
| [{"foo":"1"}] |
+---------------+
```

**Comment by NivedhaSenthil** [comment]
Thanks for reporting with details. I am able to replicate and see why this is happening will try putting in a fix sooner.
