### ISSUE TITLE
Signet::AuthorizationError on latest version

### ISSUE THREAD

**Issue by sschepens** [googleapis/google-cloud-ruby#18420]
#### Environment details

  - OS: macOS m1
  - Ruby version: 2.6.3
  - Gem name and version:

#### Steps to reproduce

  1. run `bundle update` to update to latest gems.

#### Code example

```ruby
  @instances = Google::Cloud::Compute.instances do |config|
    config.credentials = CREDENTIALS
    config.scope = ['https://www.googleapis.com/auth/cloud-platform']
  end
```

#### Full backtrace

```sh
Failure/Error:
  @instances = Google::Cloud::Compute.instances do |config|
    config.credentials = CREDENTIALS
    config.scope = ['https://www.googleapis.com/auth/cloud-platform']
  end

Signet::AuthorizationError:
  Unexpected error: #<ArgumentError: wrong number of arguments (given 2, expected 1)>
# ./vendor/bundle/ruby/2.6.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:112:in `rescue in retry_with_error'
# ./vendor/bundle/ruby/2.6.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:101:in `retry_with_error'
# ./vendor/bundle/ruby/2.6.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
# ./vendor/bundle/ruby/2.6.0/gems/googleauth-1.2.0/lib/googleauth/credentials.rb:367:in `initialize'
# ./vendor/bundle/ruby/2.6.0/gems/google-cloud-compute-v1-1.2.0/lib/google/cloud/compute/v1/instances/rest/client.rb:241:in `new'
# ./vendor/bundle/ruby/2.6.0/gems/google-cloud-compute-v1-1.2.0/lib/google/cloud/compute/v1/instances/rest/client.rb:241:in `initialize'
# ./vendor/bundle/ruby/2.6.0/gems/google-cloud-compute-0.2.0/lib/google/cloud/compute.rb:763:in `new'
# ./vendor/bundle/ruby/2.6.0/gems/google-cloud-compute-0.2.0/lib/google/cloud/compute.rb:763:in `instances'
# ./lib/gcp/gcp_client_provider.rb:9:in `<module:GcpClientProvider>'
# ./lib/gcp/gcp_client_provider.rb:4:in `<top (required)>'
# ./config/application.rb:35:in `require'
# ./config/application.rb:35:in `block in <top (required)>'
# ./config/application.rb:35:in `each'
# ./config/application.rb:35:in `<top (required)>'
# ./spec/spec_helper.rb:28:in `require_relative'
# ./spec/spec_helper.rb:28:in `<top (required)>'
# ------------------
# --- Caused by: ---
# ArgumentError:
#   wrong number of arguments (given 2, expected 1)
#   ./vendor/bundle/ruby/2.6.0/gems/rubysl-base64-2.0.0/lib/rubysl/base64/base64.rb:80:in `urlsafe_encode64'
```

**Comment by dazuma** [comment]
Looking at the underlying error, I suspect this is related instead to rubysl-base64 rather than googleauth. Can you try pinning googleauth to the previous version (e.g. 1.1.3, or whatever you were using previously) and see if the issue still happens? If so, the issue is elsewhere.

(Note that the actual Ruby standard library base64 gem name is "base64". I'm not sure what rubysl-base64 is; the last release was many years ago, and the github repo no longer exists.)

**Comment by sschepens** [comment]
@dazuma huh, thought that was the default ruby base64, but you're right, we've this since a long time and I really don't know why, removing it works. Don't know why the update broke though.

Thanks!
