### ISSUE TITLE
Exception Handling using write_log_entries

### ISSUE THREAD

**Issue by qingling128** [googleapis/google-cloud-ruby#1893]
`google-cloud-logging` Version: `v1.2.3`.

We are using `google-cloud-logging`'s [write_log_entries](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb#L371) method to make RPC calls.

For exception handling, we are expecting it to throw `Google::Gax::GaxError` only (`GRPC::BadStatus` would be wrapped in the `error.cause`). There is similar exception handling logic in https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/service.rb#L304:
```
        def execute
          yield
        rescue Google::Gax::GaxError => e
          # GaxError wraps BadStatus, but exposes it as #cause
          raise Google::Cloud::Error.from_error(e.cause)
        end
```

But in production, we observed some unhandled exception `GRPC::DeadlineExceeded` being thrown.

```
2017-12-12 07:46:01 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-12-12 07:46:02 +0000 chunk="5601fd735e321fe1296ebf9eac99a819" error_class=GRPC::DeadlineExceeded error="4:Deadline Exceeded"
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:46:in `check_status'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:178:in `attach_status_results_and_complete_call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:340:in `request_response'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/grpc-1.2.5-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:185:in `block (3 levels) in rpc_stub_class'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:325:in `call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:325:in `block in retryable'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:222:in `call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:222:in `block in create_api_call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:248:in `call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-gax-0.8.10/lib/google/gax/api_callable.rb:248:in `block in create_api_call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-cloud-logging-1.2.3/lib/google/cloud/logging/v2/logging_service_v2_client.rb:358:in `call'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/google-cloud-logging-1.2.3/lib/google/cloud/logging/v2/logging_service_v2_client.rb:358:in `write_log_entries'
  2017-12-12 07:46:01 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.2.0/gems/fluent-plugin-google-cloud-0.6.12/lib/fluent/plugin/out_google_cloud.rb:579:in `block in write'
```

After a closer look, it turns out that under the hood `write_log_entries` calls [Google::Gax.create_api_call](https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/api_callable.rb#L224).
```
            @write_log_entries = Google::Gax.create_api_call(
              @logging_service_v2_stub.method(:write_log_entries),
              defaults["write_log_entries"]
            )
```

According to their method description, it might throw `StandardError`. But that does not seem to be our case.
```
    # @raise [StandardError] if +settings+ has incompatible values,
    #   e.g, if bundling and page_streaming are both configured
    def create_api_call(func, settings, params_extractor: nil)
```

The current guess is that the `RPC` call somehow got timeout from the client side, so the error is not wrapped with `Google::Gax::GaxError` properly.

Right now we are adding a `rescue` for `StandardError` as well. But just wanna know if this is an expected behavior. Also, maybe worth revisiting the exception handling in https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/service.rb#L304 as well.

**Comment by geigerj** [comment]
This isn't expected behavior; the GAPIC layer is supposed to wrap all `GRPC::BadStatus` errors in a `Google::Gax::GaxError`.

If you have a repro case (or some code that I can run that may eventually trigger this unexpected error), that would be helpful.

FWIW `Google::Gax.create_api_call` is called only when the service object is initialized, not each time you write an entry, so it's unlikely to be the cause of this issue.

**Comment by qingling128** [comment]
@geigerj  -  I haven't been able to consistently reproduce it. The effective piece of code is as below though.

```
require "grpc"
require "google/api/monitored_resource_pb"
require "google/cloud/logging/v2"
require "google/logging/v2/log_entry_pb"
require "google/gax"
require 'googleauth'

timeout_seconds = 0.0001 # 0.000000000001
entry_count = 100 # 500000
total_repeated_time = 100

ssl_creds = GRPC::Core::ChannelCredentials.new
authentication = Google::Auth.get_application_default
creds = GRPC::Core::CallCredentials.new(authentication.updater_proc)
creds = ssl_creds.compose(creds)
logging_client = Google::Cloud::Logging::V2::LoggingServiceV2Client.new(
  channel: GRPC::Core::Channel.new('logging.googleapis.com', nil, creds),
  timeout: timeout_seconds
)

entries = []
for i in 0..entry_count
  entries << Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/google.com:sandbox-146415/logs/testgrpc',
      resource: Google::Api::MonitoredResource.new({
        type: 'gce_instance',
        labels: {
          'instance_id' => '1467652569934370213',
          'project_id' => 'google.com:sandbox-146415',
          'zone' => 'us-central1-b'
        }
      }),
      text_payload: 'testgrpc'
    })
end

count = 0
while count < total_repeated_time
  begin
    options = Google::Gax::CallOptions.new(timeout: timeout_seconds)
    logging_client.write_log_entries(
      entries,
      options: options
    )
    puts "successful"
  rescue Google::Gax::GaxError => gax_error
    puts "gax error:\n#{gax_error.inspect}\n"
  rescue => error
    puts "error:\n#{error.inspect}\n"
  end
  count += 1
end
```

I've tried to set the client side timeout to really low, yet not able to trigger a timeout. For some reason it's not taking effect (maybe the way I set it is wrong).

On the other side, I've verified that a server side timeout returns a `GaxError` correctly (by setting the entry_count to 500000).

```
gax error:
#<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 4:Deadline Exceeded>
```

**Comment by akshaymoghe** [comment]
I am consistently hitting a similar issue (`DeadlineExceeded`). Here is a sample backtrace:
```
2019-04-03 00:39:27 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2019-04-03 00:39:29 +0000 chunk="5859558452b3d29e472642286e276e01" error_class=GRPC::DeadlineExceeded error="4:Deadline Exceeded"
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:172:in `block (2 levels) in request_response'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/grpc-1.14.2-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:171:in `block in request_response'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:363:in `block in retryable'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:230:in `block in create_api_call'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:260:in `block in create_api_call'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/v2/logging_service_v2_client.rb:416:in `write_log_entries'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.7.6/lib/fluent/plugin/out_google_cloud.rb:789:in `write_request_via_grpc'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.7.6/lib/fluent/plugin/out_google_cloud.rb:721:in `call'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-google-cloud-0.7.6/lib/fluent/plugin/out_google_cloud.rb:721:in `write'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/compat/output.rb:131:in `write'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-04-03 00:39:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by blowmage** [comment]
I'll look into this.

**Comment by blowmage** [comment]
@akshaymoghe Next time you see one of these errors, can you also iteratively log the error's cause objects? I am curious about the error and how it seems to avoid the `rescue` in the `retryable` proc.

**Comment by blowmage** [comment]
Do you happen to have `Thread.abort_on_exception = true` set in your application?

**Comment by akshaymoghe** [comment]
This isn't a custom application - it is `fluentd` (obtained via debian pkgs , where it is known as `td-agent`) .

**Comment by blowmage** [comment]
@qingling128 Is this something you are still dealing with? Is `GRPC::DeadlineExceeded` the only error that is bypassing GAX?

**Comment by blowmage** [comment]
@akshaymoghe What version of fluent-plugin-google-cloud are you using?

**Comment by akshaymoghe** [comment]
Turns out this is caused by the server name being unresolvable (due to DNS errors).

It would be super useful if the error indicated that there were issues with name resolution , instead of the current message (`DeadlineExceeded`)

**Comment by blowmage** [comment]
That is good news that it wasn't caused by the client. Additional information is available in the `code`, `details`, and `metadata` values on the error object, but it doesn't look like those are being logged.

We are still trying to reproduce how a `GRPC::BadStatus` error is not being wrapped by `GaxError`, but so far I don't have an answer yet.

**Comment by qingling128** [comment]
@blowmage - We've only observed `GRPC::DeadlineExceeded` error that bypassed GAX. We could not consistently reproduce it either. `fluent-plugin-google-cloud-0.7.6` was released less than a month ago, which has the `StandardError` [rescue](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/v0.7.6/lib/fluent/plugin/out_google_cloud.rb#L907). So at least our agent should no longer crash for it. But yeah, we are still seeing the issue.

**Comment by blowmage** [comment]
The only time I've seen errors bypassing Gax is when using a stream. I'm currently working on an overhaul of Gax, and I honestly don't know where else to look to explain this behavior.

Looking at your code, you could pass both `BadStatus` and `GaxError` to the same rescue. Instead of this:

```ruby
rescue Google::Gax::GaxError => gax_error
  # GRPC::BadStatus is wrapped in error.cause.
  error = gax_error.cause
```

You could do this:

```ruby
rescue Google::Gax::GaxError, GRPC::BadStatus => error
  # We only want to deal with GRPC::BadStatus errors
  error = error.cause if error error.is_a? Google::Gax::GaxError
```

Or, if you only want to handle raw `DeadlineExceeded` errors.


```ruby
rescue Google::Gax::GaxError, GRPC::DeadlineExceeded => error
  # We only want to deal with GRPC::BadStatus errors
  error = error.cause if error error.is_a? Google::Gax::GaxError
```

**Comment by blowmage** [comment]
@qingling128 Have you seen any `GRPC::DeadlineExceeded` errors bypassing Gax since mid April?

**Comment by qingling128** [comment]
Hi @blowmage, we added a `StandardError` block as a workaround: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/200. So far the workaround has been working fine for us. I'm gonna close this one for now.
