### ISSUE TITLE
[Test Failure] Storage PRs are facing rate limit errors in acceptance tests

### ISSUE THREAD

**Issue by SandeepTuniki** [googleapis/google-cloud-ruby#19200]
The PRs for Storage have been failing on the build, because the acceptance tests were failing due to rate limit errors.

Example failure:
```
  3) Error:
Google::Cloud::Storage::Bucket::default_acl::storage#test_0005_retrieves and modifies the ACL:
Google::Cloud::ResourceExhaustedError: rateLimitExceeded: You have exceeded the rate limit for update operations on this bucket. Please slow down execution and try again.
    /workspace/google-cloud-storage/lib/google/cloud/storage/service.rb:912:in `rescue in execute'
    /workspace/google-cloud-storage/lib/google/cloud/storage/service.rb:909:in `execute'
    /workspace/google-cloud-storage/lib/google/cloud/storage/service.rb:143:in `patch_bucket'
    /workspace/google-cloud-storage/lib/google/cloud/storage/bucket/acl.rb:825:in `update_predefined_default_acl!'
    /workspace/google-cloud-storage/lib/google/cloud/storage/bucket/acl.rb:776:in `private!'
    /workspace/google-cloud-storage/acceptance/storage/bucket_default_acl_test.rb:27:in `block (3 levels) in <top (required)>'
    /workspace/google-cloud-storage/acceptance/storage_helper.rb:117:in `block in safe_gcs_execute'
    /h/.gem/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
    /h/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
    /h/.gem/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
    /workspace/google-cloud-storage/acceptance/storage_helper.rb:111:in `safe_gcs_execute'
    /workspace/google-cloud-storage/acceptance/storage/bucket_default_acl_test.rb:27:in `block (2 levels) in <top (required)>'
```

Some solutions we could implement for this:

1. Exponential backoff for failing tests.
2. Use multiple buckets to get around the rate limit for a single bucket (1 update / second).
3. Increase the delay period between tests.
4. Configure the rate limit (unsure if this is configurable per [this document](https://cloud.google.com/storage/quotas))

**Comment by SandeepTuniki** [comment]
Documenting my findings after further investigations:

> 1. Exponential backoff for failing tests.

Implemented this in #19147. The number of failing specs decreased (but not zero) with this approach.

> 2. Use multiple buckets to get around the rate limit for a single bucket (1 update / second).

This approach is useful, but I discovered that many of the failing specs are due to consecutive writes within the same test.

https://github.com/googleapis/google-cloud-ruby/blob/ad3a7f451bdee522249e432f38df650ca11da490/google-cloud-storage/acceptance/storage/bucket_default_acl_test.rb#L108-L124

So a better approach might to be have backoff for each statement.
