### ISSUE TITLE
Dynamically created GKE deployments can't authenticate using SA

### ISSUE THREAD

**Issue by jmthomas** [googleapis/google-cloud-ruby#19342]
#### Environment details

  - OS: Alpine 3.16.2
  - Ruby version: 3.0
  - Gem name and version: google-cloud-storage, 1.43

#### Steps to reproduce

  1. Follow [Workload Identify](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#yaml) tutorial
  2. Ensure configuration correct by following [Troubleshooting](https://cloud.google.com/kubernetes-engine/docs/troubleshooting/troubleshooting-security#workload-identity)
  3. Initial deployment is successful and has access to the buckets using the default service account
  4. Dynamically create deployment using ruby `kubeclient`
  5. New pod from deployment does NOT have access to buckets using the same default service account

#### Code example

```ruby
require 'google/cloud/storage'
class GcpBucket
  def initialize
    @client = Google::Cloud::Storage.new # No login info
  end
  def create(bucket)
    unless exist?(bucket)
      @client.create_bucket(bucket)
    end
    bucket
  end
  def exist?(bucket)
    if @client.bucket(bucket)
      true
    else
      false
    end
  end
end
```

#### Full backtrace

```sh
/usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:913:in `rescue in execute': forbidden: openc3-sa@<PROJECT ID>.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. (Google::Cloud::PermissionDeniedError)
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:910:in `execute'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:101:in `get_bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/project.rb:225:in `bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-enterprise-5.0.12.pre.beta0/lib/openc3/utilities/gcp_bucket.rb:41:in `exist?'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-enterprise-5.0.12.pre.beta0/lib/openc3/utilities/gcp_bucket.rb:27:in `create'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:130:in `initialize'
	from plugin_microservice.rb:26:in `initialize'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:44:in `new'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:44:in `run'
	from plugin_microservice.rb:42:in `<main>'
/usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:239:in `check_status': forbidden: openc3-sa@<PROJECT ID>.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. (Google::Apis::ClientError)
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/api_command.rb:135:in `check_status'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:202:in `process_response'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:321:in `execute_once'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:126:in `block (2 levels) in do_retry'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:123:in `block in do_retry'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/lib/ruby/gems/3.1.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:113:in `do_retry'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/http_command.rb:104:in `execute'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-core-0.9.1/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
	from /usr/lib/ruby/gems/3.1.0/gems/google-apis-storage_v1-0.19.0/lib/google/apis/storage_v1/service.rb:381:in `get_bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:102:in `block in get_bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:911:in `execute'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/service.rb:101:in `get_bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/project.rb:225:in `bucket'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-enterprise-5.0.12.pre.beta0/lib/openc3/utilities/gcp_bucket.rb:41:in `exist?'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-enterprise-5.0.12.pre.beta0/lib/openc3/utilities/gcp_bucket.rb:27:in `create'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:130:in `initialize'
	from plugin_microservice.rb:26:in `initialize'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:44:in `new'
	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.12.pre.beta0/lib/openc3/microservices/microservice.rb:44:in `run'
	from plugin_microservice.rb:42:in `<main>'
```

I have verified that the service account `openc3-sa@<PROJECT ID>.iam.gserviceaccount.com` has the Storage Admin role so I'm not sure where the disconnect is. I'm not sure why a dynamically created deployment / pod would not have access but my initial helm chart deployment does. How does `Google::Cloud::Storage.new` authenticate and get the service account credentials to enable access?

**Comment by dazuma** [comment]
Thanks for the feedback. I've forwarded your suggestion to the Cloud Storage team, as the error message originates from the Cloud Storage backend. You can track it here: https://issuetracker.google.com/issues/275066493
