### ISSUE TITLE
bucket presigned_request SignedUrlUnavailable

### ISSUE THREAD

**Issue by jmthomas** [googleapis/google-cloud-ruby#19399]
#### Environment details

  - OS: Mac OS 13.0
  - Ruby version: 3.1
  - Gem name and version: google-cloud-storage (1.43.0)

#### Steps to reproduce

  1. gcloud auth application-default login
  2. gcloud config set project <PROJECT_ID>
  3. Try to get signed request to bucket file
  4. Fail: Google::Cloud::Storage::SignedUrlUnavailable

#### Code example

```ruby
require 'google/cloud/storage'
PROJECT_ID = 'my-project-12345' # change to actual project ID
@client = Google::Cloud::Storage.new(project_id: PROJECT_ID)
@client.create_bucket("#{PROJECT_ID}_test")
bucket = @client.bucket("#{PROJECT_ID}_test")
bucket.create_file(StringIO.new('contents'), 'test')
file = @client.bucket("#{PROJECT_ID}_test").file('test')
url = file.signed_url(method: 'GET', expires: 300)
```

#### Full backtrace

```sh
irb(main):014:0> url =file.signed_url(method: 'GET', expires: 300)
/opt/homebrew/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/file/signer_v2.rb:88:in `determine_issuer': Service account credentials 'issuer (client_email)' is missing. To generate service account credentials see https://cloud.google.com/iam/docs/service-accounts (Google::Cloud::Storage::SignedUrlUnavailable)
        from /opt/homebrew/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/file/signer_v2.rb:125:in `signed_url'
        from /opt/homebrew/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.43.0/lib/google/cloud/storage/file.rb:1801:in `signed_url'
        from (irb):14:in `<main>'                       
        from /opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /opt/homebrew/opt/ruby/bin/irb:25:in `load'
        from /opt/homebrew/opt/ruby/bin/irb:25:in `<main>'
```

I'm not sure how to know which service account it's trying to use but I have a service account created in IAM with an email so I'm not sure how to proceed.

**Comment by jmthomas** [comment]
Was able to solve using code found here: https://cloud.google.com/ruby/docs/reference/google-cloud-storage/latest/Google-Cloud-Storage-File#Google__Cloud__Storage__File_signed_url_instance_

```ruby
signer = lambda do |string_to_sign|
  iam_client = Google::Apis::IamcredentialsV1::IAMCredentialsService.new

  # Get the environment configured authorization
  scopes = ["https://www.googleapis.com/auth/iam"]
  iam_client.authorization = Google::Auth.get_application_default scopes

  request = Google::Apis::IamcredentialsV1::SignBlobRequest.new(payload: string_to_sign)
  resource = "projects/-/serviceAccounts/#{ENV['GCP_SERVICE_ACCOUNT_EMAIL']}"
  response = iam_client.sign_service_account_blob resource, request
  response.signed_blob
end

url = @client.signed_url(bucket, key, method: 'GET', expires: 300, issuer: ENV['GCP_SERVICE_ACCOUNT_EMAIL'], signer: signer)
```
