### ISSUE TITLE
upgrading from 2.6.6 fails

### ISSUE THREAD

**Issue by github0013** [googleapis/google-cloud-ruby#20354]
#### Environment details

  - OS: Linux 36c9c6a81ead 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 GNU/Linux 
  - Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
  - Gem name and version:  google-cloud-firestore v2.10.0

#### Steps to reproduce

  1. bundle update google-cloud-firestore
  2. rails c

#### Full backtrace

```sh
root@36c9c6a81ead:/app# rails c
Traceback (most recent call last):
        33: from bin/rails:4:in `<main>'
        32: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        31: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        30: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/commands.rb:18:in `<main>'
        29: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/command.rb:46:in `invoke'
        28: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/command/base.rb:69:in `perform'
        27: from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        26: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        25: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        24: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/commands/console/console_command.rb:95:in `perform'
        23: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        22: from /usr/local/bundle/gems/railties-5.2.7/lib/rails/command/actions.rb:22:in `require_application!'
        21: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        20: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        19: from /app/config/application.rb:20:in `<main>'
        18: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        17: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        16: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore.rb:17:in `<main>'
        15: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        14: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        13: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/client.rb:20:in `<main>'
        12: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        11: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        10: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/collection_reference.rb:17:in `<main>'
         9: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         8: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         7: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/query.rb:20:in `<main>'
         6: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         5: from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         4: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/aggregate_query.rb:18:in `<main>'
         3: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/aggregate_query.rb:19:in `<module:Google>'
         2: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/aggregate_query.rb:20:in `<module:Cloud>'
         1: from /usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/aggregate_query.rb:60:in `<module:Firestore>'
/usr/local/bundle/gems/google-cloud-firestore-2.10.0/lib/google/cloud/firestore/aggregate_query.rb:172:in `<class:AggregateQuery>': uninitialized constant Google::Cloud::Firestore::V1::StructuredAggregationQuery (NameError)
Did you mean?  Google::Cloud::Firestore::V1::StructuredQuery
```

- 2.6.6 -> 2.7.0 OK
- 2.6.6 -> 2.7.1 OK
- 2.6.6 -> 2.7.2 OK
- 2.6.6 -> 2.8.0 BAD
- 2.6.6 -> 2.9.0 BAD
- 2.6.6 -> 2.10.0 BAD

**Comment by NivedhaSenthil** [comment]
This seems to be failing because the gem is trying to resolve to dependency ` google-cloud-firestore-v1` which is not having the expected modules. This has to be updated in the `google-cloud-firestore` gem. As a workaround can you please try updating `google-cloud-firestore-v1` gem also ?
