### ISSUE TITLE
google-analytics-data Field screenPageViews is not a valid dimension

### ISSUE THREAD

**Issue by ekortright** [googleapis/google-cloud-ruby#20438]
I'm trying to run a report listing pages on a website that uses GA4, ordered according to the number of page views.

Following the API documentation, I've created a report request specifying the `screenPageViews` dimension, but when I try to run it, a `Google::Cloud::InvalidArgumentError` is thrown, with the message:

> Did you mean screenResolution? Field screenPageViews is not a valid dimension. For a list of valid dimensions and metrics, see https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema

If you go to that page, `screenPageViews` is listed as a valid dimension.

From my experience with the YouTube Ruby API, I thought of changing `screenPageViews` to `screen_page_views` to match Ruby's variable naming convention, but the result is the same: `screen_page_views is not a valid dimension ...`.

#### Environment details

  - OS: MacOS 11.5.2
  - Ruby version: 2.7.6
  - Gem name and version: google-analytics-data (0.3.1), google-analytics-data-v1beta (0.6.0)

#### Code example

```ruby
require 'google/analytics/data'

client = Google::Analytics::Data.analytics_data { |config| config.credentials = './client-secret.json' }
request = Google::Analytics::Data::V1beta::RunReportRequest.new property: 'properties/000000000'
request.date_ranges << Google::Analytics::Data::V1beta::DateRange.new(start_date: '2023-01-01', end_date: '2023-02-01')
request.dimensions << Google::Analytics::Data::V1beta::Dimension.new(name: 'screenPageViews')
request.metrics << Google::Analytics::Data::V1beta::Metric.new(name: 'pagePath')
request.metrics << Google::Analytics::Data::V1beta::Metric.new(name: 'pageTitle')
request.order_bys << Google::Analytics::Data::V1beta::OrderBy.new(desc: true, metric: Google::Analytics::Data::V1beta::OrderBy::MetricOrderBy.new(metric_name: 'screenPageViews'))

r = client.run_report(request)
```

#### Full backtrace

```sh
2.7.6 :019 > r = client.run_report(request)
Traceback (most recent call last):
        6: from /Users/ekortright/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `<main>'
        5: from /Users/ekortright/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `load'
        4: from /Users/ekortright/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        3: from (irb):18
        2: from /Users/ekortright/.rvm/gems/ruby-2.7.6@scripts/gems/google-analytics-data-v1beta-0.6.0/lib/google/analytics/data/v1beta/analytics_data/client.rb:286:in `run_report'
        1: from /Users/ekortright/.rvm/gems/ruby-2.7.6@scripts/gems/google-analytics-data-v1beta-0.6.0/lib/google/analytics/data/v1beta/analytics_data/client.rb:324:in `rescue in run_report'
Google::Cloud::InvalidArgumentError (3:Did you mean screenResolution? Field screenPageViews is not a valid dimension. For a list of valid dimensions and metrics, see https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema . debug_error_string:{UNKNOWN:Error received from peer ipv4:172.253.62.95:443 {grpc_message:"Did you mean screenResolution? Field screenPageViews is not a valid dimension. For a list of valid dimensions and metrics, see https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema ", grpc_status:3, created_time:"2023-02-16T07:21:33.920299-06:00"}})
```

Thanks for any help, and please let me know if I can provide any more information.

**Comment by ekortright** [comment]
It's not a valid dimension, it's a metric.  (Slaps forehead)
