### ISSUE TITLE
Bigtable acceptance tests failing

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2460]
We are seeing failures on CI while running the Bigtable acceptance tests.

```
****************************************
*** google-cloud-bigtable acceptance ***
****************************************

"=> 'google-cloud-ruby-tests' instance is ready."
Run options: --seed 58230

# Running:

..............................EE......................

Finished in 38.766524s, 1.3930 runs/s, 6.2167 assertions/s.

  1) Error:
Table drop rows::bigtable#test_0001_delete all rows:
Google::Cloud::DeadlineExceededError: 4:Insufficient deadline for DropRowRange. Please try again with a longer request deadline.
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:699:in `rescue in execute'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:696:in `execute'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:517:in `drop_row_range'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:597:in `drop_row_range'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:549:in `delete_all_rows'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/table/drop_rows_test.rb:24:in `block (2 levels) in <top (required)>'

  2) Error:
Table drop rows::bigtable#test_0002_delete rows by prefix:
Google::Cloud::DeadlineExceededError: 4:Insufficient deadline for DropRowRange. Please try again with a longer request deadline.
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:699:in `rescue in execute'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:696:in `execute'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:517:in `drop_row_range'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:597:in `drop_row_range'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb:570:in `delete_rows_by_prefix'
    /home/circleci/GoogleCloudPlatform/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/table/drop_rows_test.rb:33:in `block (2 levels) in <top (required)>'

54 runs, 241 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by blowmage** [comment]
@jiren Do you know anything about this? The PR #2454 just changed the connection values for this endpoint. 

it was previously configured with this:

```json
{
  "initial_retry_delay_millis": 100,
  "retry_delay_multiplier": 1.3,
  "max_retry_delay_millis": 60000,
  "initial_rpc_timeout_millis": 900000,
  "rpc_timeout_multiplier": 1.0,
  "max_rpc_timeout_millis": 900000,
  "total_timeout_millis": 3600000
}
```

But it is now configured with this:

```json
{
  "initial_retry_delay_millis": 100,
  "retry_delay_multiplier": 1.3,
  "max_retry_delay_millis": 60000,
  "initial_rpc_timeout_millis": 20000,
  "rpc_timeout_multiplier": 1.0,
  "max_rpc_timeout_millis": 20000,
  "total_timeout_millis": 600000
}
```

**Comment by blowmage** [comment]
cc @sduskis

**Comment by jiren** [comment]
@blowmage "drop rows" is an admin operation and it takes significant amount of time. So when default request deadline time is not sufficient to perform drop rows then BigTable respond with increase deadline timeout error.
