### ISSUE TITLE
Unable to add defs to DescriptorPool: couldn't resolve name '.google.api.MonitoredResourceMetadata' in message 'google.monitoring.v3.TimeSeries'

### ISSUE THREAD

**Issue by jrun** [googleapis/google-cloud-ruby#2498]
After upgrading the google-cloud-monitoring gem from version `0.28.0` to `0.29.2`, I'm receiving what appears to be a protobuf related error while loading the library. 

Here are a couple of examples which demonstrate the problem:

```ruby
irb(main):001:0> require 'google/cloud/monitoring/v3'
RuntimeError: Unable to add defs to DescriptorPool: couldn't resolve name '.google.api.MonitoredResourceMetadata' in message 'google.monitoring.v3.TimeSeries'

        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `finalize_to_pool'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `build'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_service_pb.rb:11:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/cloud/monitoring/v3/metric_service_client.rb:28:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/cloud/monitoring/v3.rb:18:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/bin/irb:11:in `<main>'        
```

```ruby
irb(main):001:0> require 'google/cloud/monitoring'
=> true
irb(main):002:0> require 'google/cloud/monitoring/v3'
RuntimeError: Unable to add defs to DescriptorPool: couldn't resolve name '.google.api.MonitoredResourceMetadata' in message 'google.monitoring.v3.TimeSeries'

        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `finalize_to_pool'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `build'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_pb.rb:12:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/monitoring/v3/metric_service_pb.rb:11:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/cloud/monitoring/v3/metric_service_client.rb:28:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-monitoring-0.29.2/lib/google/cloud/monitoring/v3.rb:18:in `<top (required)>'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from (irb):2
        from /Users/redacted/.rbenv/versions/ruby-2.3.1/bin/irb:11:in `<main>'
```

Installed Google related gems: 

```
★  gem list | ag google
google-api-client (0.24.2)
google-cloud-core (1.2.7)
google-cloud-env (1.0.0)
google-cloud-error_reporting (0.30.5, 0.30.0)
google-cloud-monitoring (0.29.2)
google-cloud-storage (1.14.2)
google-cloud-trace (0.33.5, 0.33.0)
google-gax (1.4.0, 1.0.1)
google-protobuf (3.6.1 universal-darwin)
googleapis-common-protos (1.3.5)
googleapis-common-protos-types (1.0.2, 1.0.1)
googleauth (0.6.2)
```

**Comment by jrun** [comment]
I had previously reinstalled select gems. Given you can't repro, I purged all installed gems and reinstalled everything. It worked outside of the Rails app in question but not within.  I found a couple of transient dependencies that I missed and tried again and it worked (🙄 ).

Not sure exactly what happened but I suspect upgrading googleapis-common-protos from 1.3.5 to 1.37 played a part in resolving the problem.

Thanks for your help and sorry for the noise.

**Comment by blowmage** [comment]
Glad you got it working!
