### ISSUE TITLE
Bug in BigQuery partitioned tables doc examples

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2520]
Doc examples show [query jobs with time partitioning](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L906-L922) but no destination table, which results in the following error:

```sh
Google::Cloud::Bigquery::bigquery#test_0004_sends query results to a clustered destination table:
Google::Cloud::InvalidArgumentError: invalid: If partitioning specification is present, destination table must also be present.
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:413:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:407:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:280:in `query_job'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/project.rb:351:in `query_job'
```

In these examples, a destination table must be set.

**Comment by quartzmo** [comment]
Doc examples show [query jobs with time partitioning](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L906-L922) but no destination table, which results in the following error:

```sh
Google::Cloud::Bigquery::bigquery#test_0004_sends query results to a clustered destination table:
Google::Cloud::InvalidArgumentError: invalid: If partitioning specification is present, destination table must also be present.
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:413:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:407:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:280:in `query_job'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/project.rb:351:in `query_job'
```

In these examples, a destination table must be set.
