### ISSUE TITLE
Google::Cloud::InvalidArgumentError: 3:ReportedErrorEvent.context must contain a location unless `message` contain an exception or stacktrace.

### ISSUE THREAD

**Issue by stabenfeldt** [googleapis/google-cloud-ruby#2746]
#### Environment details

  - OS
    - Ubuntu (ruby:2.4-slim-jessie)
  - Ruby version
     -  ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
  - Gem name and version:
    - stackdriver (0.15.0)
    - stackdriver-core (1.3.0)

#### Steps to reproduce

  1. Give the service acount "Compute Engine default service account" access to Stackdriver API.
  2. Log into a kubernetes node and start rails console
  3. Run this code: `Google::Cloud::ErrorReporting.report Exception.new(msg: "from console")`
  
That returns this error:
```ruby
=> nil
irb(main):006:0> {:msg=>"from console"} (Exception)
Google::Cloud::InvalidArgumentError: 3:ReportedErrorEvent.context must contain a location unless `message` contain an exception or stacktrace.
        /usr/local/bundle/gems/google-cloud-error_reporting-0.30.2/lib/google/cloud/error_reporting/service.rb:94:in `rescue in execute'
        /usr/local/bundle/gems/google-cloud-error_reporting-0.30.2/lib/google/cloud/error_reporting/service.rb:90:in `execute'
        /usr/local/bundle/gems/google-cloud-error_reporting-0.30.2/lib/google/cloud/error_reporting/service.rb:79:in `report'
        /usr/local/bundle/gems/google-cloud-error_reporting-0.30.2/lib/google/cloud/error_reporting/project.rb:126:in `report'
        /usr/local/bundle/gems/google-cloud-error_reporting-0.30.2/lib/google/cloud/error_reporting/async_error_reporter.rb:83:in `run_backgrounder'
        /usr/local/bundle/gems/stackdriver-core-1.3.0/lib/stackdriver/core/async_actor.rb:291:in `async_run_job'
        /usr/local/bundle/gems/stackdriver-core-1.3.0/lib/stackdriver/core/async_actor.rb:315:in `block (2 levels) in ensure_thread'
```

There are no specifications to how an exception should look like according to [the docs](https://cloud.google.com/error-reporting/docs/setup/ruby):
```ruby

require "google/cloud/error_reporting"

begin
  fail "Raise an exception for Error Reporting."
rescue => exception
  Google::Cloud::ErrorReporting.report exception
end

```

**Comment by stabenfeldt** [comment]
Digging around the source code I found an [example](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/lib/google/cloud/error_reporting/service.rb#L52-L70) for reporting errors:

        #   error_event =
        #     error_reporting.error_event "Error Message with Backtrace",
        #                                 event_time: Time.now,
        #                                 service_name: "my_app_name",
        #                                 service_version: "v8",
        #                                 user: "johndoh",
        #                                 file_path: "MyController.rb",
        #                                 line_number: 123,
        #                                 function_name: "index"
        #   error_reporting.report error_event

I ran this code from rails console:
```ruby
error_reporting.report error_event
=> <Google::Devtools::Clouderrorreporting::V1beta1::ReportErrorEventResponse: >
```

I can confirm that this error turned up in https://console.cloud.google.com/errors/.
Case closed :-)

**Comment by stabenfeldt** [comment]
As a consumer of open source, I strive to give feedback and small patches wherever I can. Fun to see that I lead to a patch and improvement of the software! 🎉 😀
