### ISSUE TITLE
Kokoro OS X Authentication Problem

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-ruby#2986]
The master and nightly OS X builds are failing when running the full acceptance tests. It looks like the authentication is missing or not set up correctly. Here is the build output:

```
*****************************************
*** google-cloud-container acceptance ***
*****************************************
Run options: --seed 61366
# Running:
ERROR: (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:
  $ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
  $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
E
Finished in 1.065550s, 0.9385 runs/s, 0.0000 assertions/s.
  1) Error:
ClusterManagerSmokeTest v1#test_0001_runs one smoke test with list_clusters:
Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."
}
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1017:in `fetch_access_token'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1036:in `fetch_access_token!'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/signet.rb:79:in `fetch_access_token!'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:80:in `initialize'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:124:in `new'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:124:in `block in from_json_vars'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:123:in `each'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:123:in `from_json_vars'
    /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/googleauth-0.8.0/lib/googleauth/credentials.rb:92:in `default'
    /Volumes/BuildData/tmpfs/src/github/google-cloud-ruby/google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb:105:in `initialize'
    /Volumes/BuildData/tmpfs/src/github/google-cloud-ruby/google-cloud-container/lib/google/cloud/container/v1.rb:144:in `new'
    /Volumes/BuildData/tmpfs/src/github/google-cloud-ruby/google-cloud-container/lib/google/cloud/container/v1.rb:144:in `new'
    /Volumes/BuildData/tmpfs/src/github/google-cloud-ruby/google-cloud-container/lib/google/cloud/container.rb:148:in `new'
    /Volumes/BuildData/tmpfs/src/github/google-cloud-ruby/google-cloud-container/acceptance/google/cloud/container/v1/cluster_manager_smoke_test.rb:29:in `block (2 levels) in <top (required)>'
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
```

**Comment by blowmage** [comment]
This has been resolved.
