### ISSUE TITLE
Bigquery load_job: Google::Cloud::Error "execution expired"

### ISSUE THREAD

**Issue by le0pard** [googleapis/google-cloud-ruby#3235]
#### Environment details

  - OS: Ubuntu 14.04
  - Ruby version: 2.6.2
  - Gem name and version: google-cloud-bigquery 1.11.0

#### Steps to reproduce

Happen randomly. Not sure is this issue of a gem or Google cloud itself. Maybe gem need provide more info in backtrace.

Files is not big (30 MB max) and issue happen in `dataset.load_job` bigquery, which expected just launch job on bigquery, but raise this error. 

#### Code example

```ruby
    storage_path = "bigquery/#{table}.csv.gz"
    bucket.create_file file.path, storage_path
    dataset = bigquery.dataset bigquery_dataset_id
    gcs_uri = "gs://#{bigquery_analytic_bucket}/#{storage_path}"
    dataset.load_job( # <--- 101 line in file
      table,
      gcs_uri,
      format: 'csv',
      jagged_rows: true,
      quoted_newlines: true,
      create: 'needed',
      autodetect: true,
      write: 'truncate',
      encoding: 'UTF-8',
      skip_leading: 1
    )
```

#### Full backtrace

```sh
A Google::Cloud::Error occurred in background at 2019-04-26 01:01 :

  execution expired
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/service.rb:435:in `rescue in execute'

-------------------------------
Backtrace:
-------------------------------

  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/service.rb:435:in `rescue in execute'
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/service.rb:428:in `execute'
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/service.rb:313:in `load_table_gs_url'
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/dataset.rb:2217:in `load_storage'
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/dataset.rb:2239:in `load_local_or_uri'
  /shared/bundle/ruby/2.6.0/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/dataset.rb:1474:in `load_job'
  /releases/20190425142730/app/services/analytic/bigquery_service.rb:101:in `csv_to_bigquery'
  /releases/20190425142730/app/services/analytic/bigquery_service.rb:77:in `table_to_bigquery'
  /releases/20190425142730/app/services/analytic/bigquery_service.rb:63:in `block in call'
  /releases/20190425142730/app/services/analytic/bigquery_service.rb:62:in `each'
  /releases/20190425142730/app/services/analytic/bigquery_service.rb:62:in `call'
  /releases/20190425142730/app/workers/tracking_pg_to_bigquery_worker.rb:9:in `perform'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
  /shared/bundle/ruby/2.6.0/gems/sentry-raven-2.9.0/lib/raven/integrations/sidekiq.rb:9:in `call'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
  /shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  /shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
  /shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
  /shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
  /shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
  /shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
  /shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
  /shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Thanks!

**Comment by blowmage** [comment]
It is hard to say what caused this with the information you posted. I would try recursively logging each `Error#cause` and it’s backlog as well. Also, any of the error attributes that have values such as `#status_code`, `#header`, or `#body`.

**Comment by le0pard** [comment]
@blowmage thanks. In this case I will close issue. More info in backtrace will help.

**Comment by blowmage** [comment]
That said, it looks like it could be a timeout, so one option is to pass a larger `timeout` value when creating the client object.

**Comment by le0pard** [comment]
@blowmage What is default timeout? 

https://github.com/googleapis/google-cloud-ruby/blob/2dacea929edb834345047959035f989c1341edb0/google-cloud-bigquery/OVERVIEW.md#configuring-retries-and-timeout - I can try to increase it, as I can see by doc

**Comment by blowmage** [comment]
I believe the default timeout is 60 seconds.

**Comment by le0pard** [comment]
@blowmage thanks!
