### ISSUE TITLE
Transmit to Stackdriver Trace failed: NoMethodError: undefined method nsec

### ISSUE THREAD

**Issue by directionless** [googleapis/google-cloud-ruby#3299]
#### Environment details

  - OS: Mac, Linux, Etc
  - Ruby version: ruby 2.6.1p33
  - Gem name and version:

stackdriver (0.15.3)
google-cloud-trace (0.34.2)

#### Steps to reproduce

I'm not sure what the minimum test case is here. I'm using rails, so this is tied in there.

#### Full backtrace

No backtrace, but my rails has started logging:

```
Transmit to Stackdriver Trace failed: #<NoMethodError: undefined method `nsec' for 2034920.486532:Float\nDid you mean?  inspect>
```

**Comment by directionless** [comment]
Patching my `google/cloud/trace/utils.rb` to emit a stack trace, I see that that function is sometimes called with a time object, and sometimes called with a Float. 

When it's called with a float, some of the stack trace is:
```
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/utils.rb:34:in `backtrace'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/utils.rb:34:in `time_to_grpc'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/span.rb:180:in `to_grpc'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/trace_record.rb:112:in `block in to_grpc'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/trace_record.rb:111:in `map'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/trace_record.rb:111:in `to_grpc'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:346:in `addl_bytes_for'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:317:in `try_add'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:77:in `block (2 levels) in patch_traces'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:74:in `each'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:74:in `block in patch_traces'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/async_reporter.rb:73:in `patch_traces'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/middleware.rb:245:in `send_trace'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-cloud-trace-0.34.2/lib/google/cloud/trace/middleware.rb:193:in `call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/executor.rb:14:in `call'
web            | /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
...
```
