### ISSUE TITLE
Datastore entity saves fail when using google-gax (1.6.1)

### ISSUE THREAD

**Issue by bmclean** [googleapis/google-cloud-ruby#3429]
Using `google-cloud-datastore (1.5.2)` I ran a bundle update today which upgraded `google-gax` from version 1.5.0 to 1.6.1. Our test suite had multiple occurrences of:

```ruby
TypeError: can't convert nil into an exact number
```
I reverted to `google-gax (1.5.0)` and everything worked correctly.

The TypeError is thrown when a dataset save is attempted. Any idea what might be happening? What other info can I provide that would help?

**Comment by quartzmo** [comment]
https://rubygems.org/gems/google-gax/versions/1.6.2

**Comment by quartzmo** [comment]
This issue also affected google-cloud-firestore

**Comment by quartzmo** [comment]
A Firestore backtrace:

```sh
TypeError: can't convert nil into an exact number
    /Users/quartzmo/.rbenv/versions/2.4.5/gemsets/quartzmo/gems/google-gax-1.6.1/lib/google/gax/api_callable.rb:397:in `+'
    /Users/quartzmo/.rbenv/versions/2.4.5/gemsets/quartzmo/gems/google-gax-1.6.1/lib/google/gax/api_callable.rb:397:in `block in add_timeout_arg'
    /Users/quartzmo/.rbenv/versions/2.4.5/gemsets/quartzmo/gems/google-gax-1.6.1/lib/google/gax/api_callable.rb:230:in `block in create_api_call'
    /Users/quartzmo/.rbenv/versions/2.4.5/gemsets/quartzmo/gems/google-gax-1.6.1/lib/google/gax/api_callable.rb:260:in `block in create_api_call'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb:374:in `begin_transaction'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/service.rb:132:in `block in begin_transaction'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/service.rb:188:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/service.rb:131:in `begin_transaction'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/transaction.rb:273:in `start'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/transaction.rb:56:in `initialize'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb:531:in `new'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb:531:in `transaction'
```

**Comment by bmclean** [comment]
@quartzmo Thank you! Yes, google-gax (1.6.2) looks good.
