### ISSUE TITLE
"NaN" -> Float not tolerated by bigquery's convert.rb:88

### ISSUE THREAD

**Issue by nicodemus26** [googleapis/google-cloud-ruby#3488]
#### Environment details

  - OS: linux
  - Ruby version: 2.6.1
  - Gem name and version: google-cloud-bigquery-1.11.0

#### Steps to reproduce

Run a query such as: 
```sql
SELECT
  CAST("NaN" as FLOAT64) as not_a_number,
  CAST("+inf" as FLOAT64) as positive_infinity,
  CAST("-inf" as FLOAT64) as negative_infinity
```

#### Code example

```ruby
$ irb
irb(main):004:0> Float "NaN"
Traceback (most recent call last):
        6: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `<main>'
        5: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `load'
        4: from /home/nicodemus/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):4
        2: from (irb):4:in `rescue in irb_binding'
        1: from (irb):4:in `Float'
ArgumentError (invalid value for Float(): "NaN")
irb(main):005:0> Float "Infinity"
Traceback (most recent call last):
        6: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `<main>'
        5: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `load'
        4: from /home/nicodemus/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):5
        2: from (irb):5:in `rescue in irb_binding'
        1: from (irb):5:in `Float'
ArgumentError (invalid value for Float(): "Infinity")
irb(main):006:0> Float "-Infinity"
Traceback (most recent call last):
        6: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `<main>'
        5: from /home/nicodemus/.rbenv/versions/2.6.1/bin/irb:23:in `load'
        4: from /home/nicodemus/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):6
        2: from (irb):6:in `rescue in irb_binding'
        1: from (irb):6:in `Float'
ArgumentError (invalid value for Float(): "-Infinity")
```

#### Full backtrace

```sh
 message: "invalid value for Float(): "NaN""     
    name: "ArgumentError"     
    stack_trace: [
     0:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:88:in `Float'"      
     1:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:88:in `format_value'"      
     2:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:61:in `block in format_row'"      
     3:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `map'"      
     4:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `format_row'"      
     5:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:81:in `format_value'"      
     6:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:61:in `block in format_row'"      
     7:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `map'"      
     8:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `format_row'"      
     9:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:81:in `format_value'"      
     10:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:61:in `block in format_row'"      
     11:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `map'"      
     12:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:60:in `format_row'"      
     13:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:53:in `block in format_rows'"      
     14:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:51:in `map'"      
     15:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/convert.rb:51:in `format_rows'"      
     16:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/data.rb:462:in `from_gapi_json'"      
     17:  "/usr/local/rvm/gems/ruby-2.6.1/gems/google-cloud-bigquery-1.11.0/lib/google/cloud/bigquery/query_job.rb:590:in `data'"      
 18: entrypoint...
```

**Comment by blowmage** [comment]
Thanks for the bug report. I'll get a fix out for this soon.

**Comment by nicodemus26** [comment]
Thanks, you're awesome!
