### ISSUE TITLE
When a column is added to the schema, inserts containing that field are only sometimes rejected with "no such field." for many seconds after

### ISSUE THREAD

**Issue by buzzware** [googleapis/google-cloud-ruby#3805]
I want to write a script that imports a data stream into BigQuery. When a column is added in the data, the script should add a column to the BQ schema and continue.
Unfortunately however, BQ is misbehaving after adding a column for a random amount of time, and I don't see a way to reliably know when the column is ready to be used reliably.
The API Table.fields method returns the added column immediately, but adding data with the field throws "no such field.".
Even more concerning is that it succeeds and fails multiple times before eventually settling down.
I am calling Table.reload! in the loop every time.

How is this supposed to be done?

#### Environment details

  - OS: OSX
  - Ruby version: 2.2.5
  - Gem name and version: google-cloud-bigquery 1.13.0

```
require 'rails_helper'

require "google/cloud/bigquery"
require 'csv'
Rails.logger.level = Logger::INFO


class BigqueryUploader

	COLUMN_TYPES = %w(integer timestamp float string numeric boolean bytes time datetime date)

	attr_reader :project,:location,:dataset_name,:table_name,:bigquery

	def initialize(aProject,aDatasetName,aTableName,aLocation='australia-southeast1')
		@project = aProject
		@location = aLocation
		@dataset_name = aDatasetName
		@table_name = aTableName
		@bigquery = Google::Cloud::Bigquery.new(project: @project, timeout: 0)
	end

	def reconnect
		@bigquery = Google::Cloud::Bigquery.new(project: @project, timeout: 0)
		@dataset = nil
		@table = nil
	end

	def dataset
		@dataset = @bigquery.dataset(@dataset_name) || @bigquery.create_dataset(@dataset_name,location: @location)
	end

	def table
		@table = dataset.table(@table_name, skip_lookup: false) unless @table
		@table
	end

	# there's a problem where inserting rows after deleting and recreating a table; the rows never appear
	def truncate
		table.delete
		#@bigquery.query "TRUNCATE TABLE `#{@table_name}`" if @dataset.table(@table_name)
	end

	def drop_table
		dataset.table(@table_name).delete if dataset.table(@table_name)
		@table = nil
	end

	def column_names
		table.fields.map(&:name).map(&:to_sym)
	end

	# aSchema eg.
	# [
	# 	{
	# 		'name' => 'id',
	# 		'type' => 'integer'
	# 	},
	# 	{
	# 		'name' => 'created_at',
	# 		'type' => 'timestamp',
	# 		'mode' => 'REQUIRED'
	# 	}
	# ]
	#
	# Columns in aSchema that don't already exist will be appended. Existing columns will not be affected
	def ensure_schema(aSchema,aPartitioningField)
		aSchema = aSchema.map(&:symbolize_keys)
		if !table
			@table = @dataset.create_table @table_name do |t|
				t.name = @table_name
				t.description = @table_name
				# t.time_partitioning_type = "DAY"
				# t.time_partitioning_field = aPartitioningField
				t.schema do |schema|
					schema.load aSchema
				end
			end
		else
			table_columns = column_names
			new_columns = aSchema.select {|col| not table_columns.include? col[:name].to_sym}
			unless new_columns.empty?
				table.schema(replace: false) do |schema|
					new_columns.each do |col|
						type = col[:type].downcase
						next unless COLUMN_TYPES.include? type
						schema.send(type, col[:name], description: col[:description], mode: col[:mode])
					end
					#schema.load new_columns

				end
				table.reload!
				#@table = @dataset.table(@table_name, skip_lookup: false)
				#puts 'after'
			end
		end
	end

	# create a view
	# require "google/cloud/bigquery"
	#
	# bigquery = Google::Cloud::Bigquery.new
	# dataset = bigquery.dataset "my_dataset"
	# view = dataset.create_view "my_view",
	# 													 "SELECT name, age FROM `my_project.my_dataset.my_table`"
	# view.view? # true

	# potential load method (not using since it ignores the headers):
	#
	# file = File.open THIS_DIR+'/../../house_samples.csv'
	# # Load data into the table from Google Cloud Storage
	# response = table.load file do |f|		 #"gs://my-bucket/file-name.csv"
	# 	f.format = 'csv'
	# 	f.skip_leading = 1
	# 	f.create = 'never'
	# 	f.write = 'append'
	# 	f.jagged_rows = true
	# 	f.quoted_newlines = true
	# 	f.ignore_unknown = true
	# end
	#
	# Note! for partition field, can only stream to date range within 365 days in the past and 183 days in the future relative to the current date.
	def insert_rows(aRows)
		aRows = [aRows] unless aRows.is_a? Array
		columns = column_names
		aRows = aRows.map{|r| r.slice(*columns)}

		response = table.insert(aRows,skip_invalid: false,ignore_unknown: false)
		if !response.success?
			messages = response.insert_errors.map(&:errors).flatten.map{|e|e['message']}
			messages.each do |m|
				::Rails.logger.error m
			end
			raise ::StandardError.new(messages.first)
		end
		response


		# inserter = @dataset.insert_async(@table_name) do |result|
		# 	if result.error?
		# 		puts result.error
		# 	else
		# 		puts "inserted #{result.insert_count} rows " \
		# 			"with #{result.error_count} errors"
		# 	end
		# end
		# response = inserter.insert aRows
		# response = inserter.flush.wait!
		# response
	end

	def insert_csv_file(aFile,aBatchSize=1000)
		rows = []
		table_columns = column_names
		count = 0
		CSV.foreach(aFile,{headers: true}) do |row|
			row = row.to_h
			row.slice!(*table_columns)
			puts row['created_at']
			rows << row
			if rows.length==aBatchSize
				insert_rows(rows)
				rows = []
			end
			count += 1
		end
		count
	end

	def pipe_records(aModel, aMarkColumn, aLimit=1000)
		now = Time.now
		to_upload = aModel.order(:created_at).where("#{aMarkColumn} IS NULL").limit(aLimit)
		to_upload = to_upload.map do |r|
			r = r.attributes.merge(aMarkColumn.to_s => now.utc.to_sql_format)
			r['created_at'] = r['created_at'].utc.to_sql_format
			r.symbolize_keys!
		end
		insert_rows(to_upload)
		aModel.where('id in (?)',to_upload.map{|h| h[:id]}).update_all(["#{aMarkColumn} = ?",now])
		to_upload
	end

end




describe 'BigQuery RnD' do

	it 'can wait for column to be added' do
		table_name = "test_table_#{Random.rand(1000000)}"
		puts table_name
		uploader = BigqueryUploader.new('cusp-white-gum-valley','joshshouse_test',table_name,'australia-southeast1')

		uploader.ensure_schema([
														 {name: 'id', type: 'integer'},
														 {name: 'created_at', type: 'timestamp',mode: 'REQUIRED'}
													 ],'created_at')

		time = Time.new.beginning_of_day
		row1_values = {id: 1,created_at: time.to_sql_format}
		uploader.insert_rows(row1_values)
		rows = uploader.table.data.all.to_a
		rows.length.should == 1
		rows.first[:id].should == row1_values[:id]

		# uploader.ensure_schema([
		# 												 {name: 'id', type: 'integer'},
		# 												 {name: 'created_at', type: 'timestamp',mode: 'REQUIRED'},
		# 												 {name: 'power_wh', type: 'float'}
		# 											 ],:created_at)

		def random_row
			{id: Random.rand(9999999999).to_i,created_at: (Time.now.beginning_of_day + Random.rand(999999).to_i.seconds).to_sql_format,power: Random.rand(999.9)}
		end

		puts "column_names="+uploader.column_names.join(',')
		puts "adding power column"
		uploader.table.schema(replace: false) do |schema|
			schema.float 'power'
		end

		100.times do
			begin
				uploader.insert_rows(random_row)
				puts "insert SUCCESS"
			rescue => e
				puts("insert FAILED")
			end
			puts "column_names="+uploader.column_names.join(',')

			puts "wait 2"
			sleep 2
			puts "reload!"
			uploader.table.reload!
		end

	end

end

```

#### Full backtrace

```sh
Testing started at 18:39 ...
/bin/bash -c "/Users/gary/.rvm/bin/rvm ruby-2.2.5 do bundle exec /Users/gary/.rvm/rubies/ruby-2.2.5/bin/ruby /Users/gary/repos/grigg/grigg/bin/rspec /Users/gary/repos/grigg/grigg/spec/bigquery_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --example \"BigQuery RnD can wait for column to be added\" --no-color"
Warning! PATH is not properly set up, '/Users/gary/.rvm/gems/ruby-2.3.1/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.3.1'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /Users/gary/repos/grigg/grigg/config/application.rb:7)
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/gary/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
D, [2019-08-17T18:39:08.412287 #71858] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
WARNING: You are running Ruby 2.2.5, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
Run options: include {:full_description=>/BigQuery\ RnD\ can\ wait\ for\ column\ to\ be\ added/}
column_names=id,created_at
adding column
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:39:28.552837 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:39:33.822130 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:39:44.431041 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:39:47.031794 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:39:49.599021 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:40:00.131348 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:40:08.072444 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:40:10.707296 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:40:18.768779 #71858] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!

1 example, 0 failures, 1 passed

Finished in 273.59443 seconds

Process finished with exit code 0


Testing started at 18:52 ...
/bin/bash -c "/Users/gary/.rvm/bin/rvm ruby-2.2.5 do bundle exec /Users/gary/.rvm/rubies/ruby-2.2.5/bin/ruby /Users/gary/repos/grigg/grigg/bin/rspec /Users/gary/repos/grigg/grigg/spec/bigquery_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --example \"BigQuery RnD can wait for column to be added\" --no-color"
Warning! PATH is not properly set up, '/Users/gary/.rvm/gems/ruby-2.3.1/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.3.1'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /Users/gary/repos/grigg/grigg/config/application.rb:7)
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/gary/.rvm/gems/ruby-2.2.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
D, [2019-08-17T18:52:47.853364 #72129] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
WARNING: You are running Ruby 2.2.5, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
Run options: include {:full_description=>/BigQuery\ RnD\ can\ wait\ for\ column\ to\ be\ added/}
test_table_385924
column_names=id,created_at
adding power column
E, [2019-08-17T18:52:56.945827 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:52:59.555249 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:02.128923 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:04.776492 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:07.344410 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:09.999518 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:12.595581 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:15.169954 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:17.839980 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:20.520265 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:23.117466 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:25.674915 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:28.243218 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:30.888758 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:33.551775 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:36.213273 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:38.787345 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:41.758904 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:44.336517 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:46.919995 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:49.526422 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:52.090420 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:54.653425 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:53:57.230218 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:54:48.486981 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
E, [2019-08-17T18:57:09.042131 #72129] ERROR -- : no such field.
insert FAILED
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!
insert SUCCESS
column_names=id,created_at,power
wait 2
reload!

1 example, 0 failures, 1 passed

Finished in 273.480205 seconds

Process finished with exit code 0


```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by buzzware** [comment]
I made the insert_rows method catch "no such field." errors and retry. Fortunately inserting an array of rows is atomic, so the following code seems to be working reliably without duplicate or missing rows :

```
	def insert_defensive(aRows)
		attempts = 10
		while attempts>0 do
			puts "attempt insert"
			response = table.insert(aRows,skip_invalid: false,ignore_unknown: false)
			if response.success?
				puts "insert SUCCESS"
				attempts = 0
			else
				puts "insert FAILED"
				errors = response.insert_errors.map(&:errors).flatten.select{|e| e['reason'] != 'stopped'}
				messages = errors.map{|e|e['message']}
				messages.each do |m|
					::Rails.logger.error m
				end
				if attempts==1
					raise ::StandardError.new(messages.first)
				else
					new_field_error = messages.include?('no such field.')
					if new_field_error
						sleep 30
					else
						sleep 5
					end
				end
			end
			attempts -= 1
		end
	end

	def insert_rows(aRows)
		aRows = [aRows] unless aRows.is_a? Array
		columns = column_names
		aRows = aRows.map{|r| r.slice(*columns)}
		insert_defensive(aRows)
	end

```

**Comment by blowmage** [comment]
Hello again @buzzware, I didn't notice this issue over the weekend. Similar to #3799, the answer here is that this is a known issue when streaming rows to BigQuery after a metadata change, like dropping/recreating a table, or adding a new column.

[BigQuery Troubleshooting: Metadata errors for streaming inserts](https://cloud.google.com/bigquery/troubleshooting-errors#metadata-errors-for-streaming-inserts) says:

> Because BigQuery's streaming API is designed for high insertion rates, modifications to the underlying table metadata exhibit are eventually consistent when interacting with the streaming system. In most cases metadata changes are propagated within minutes, but during this period API responses may reflect the inconsistent state of the table.

This appears to be the nature of BigQuery as an eventually consistent datastore, and not an issue with the Ruby client.

**Comment by buzzware** [comment]
1) I didn't come across any documentation warning about this behaviour, or solutions to it, so that should be addressed.
2) The backend appears to know about the new field immediately (or is the client faking that?). If so, the backend should be able to accept inserts and queue them transparently, not reject the insertion.
3) What is the recommended best practice for automatically expanding the schema ? Is my approach above reasonable? Is insert guaranteed to be atomic/transactional? If so, I guess certain errors (which ones?) can be retried until success without duplicated or missing data. 
4) Is an automatically expanding the schema possible with the Data Transfer Service, or am I doing the right thing using the API?
5) Is there any way of knowing when the eventual consistency has settled?

**Comment by blowmage** [comment]
> 1. I didn't come across any documentation warning about this behaviour, or solutions to it, so that should be addressed.

Agreed. We can update the documentation for methods that use the Streaming API and note this known issue.

> 2. The backend appears to know about the new field immediately (or is the client faking that?). If so, the backend should be able to accept inserts and queue them transparently, not reject the insertion.

Like I said before, the Streaming API is eventually consistent in nature. Different RPCs have different usage quota and performance characteristics. (See [Quotas and limits: API requests](https://cloud.google.com/bigquery/quotas#api_requests).) In fact, BigQuery, like most Cloud APIs, are not atomic, but eventually consistent. (Some APIs just happen to be eventually consistent very, very quickly.) BigQuery Schema changes are going add friction because there will be a window of time where the changes are not yet consistently applied across all of BigQuery. The Streaming API that is used to insert rows has a larger window where the changes may not be applied than the API used to describe the table's schema.

> 3. What is the recommended best practice for automatically expanding the schema ? Is my approach above reasonable? Is insert guaranteed to be atomic/transactional? If so, I guess certain errors (which ones?) can be retried until success without duplicated or missing data.

This is difficult for me to answer because I am not on the BigQuery team and I don't have the breadth of understanding about BigQuery that they do. I would suggest that frequent metadata/schema changes in BigQuery is an anti-pattern.

> 4. Is an automatically expanding the schema possible with the Data Transfer Service, or am I doing the right thing using the API?

I'm not sure I fully understand what you are trying to accomplish by using frequent metadata/schema changes and so I can't speak to what possible alternatives are.

> 5. Is there any way of knowing when the eventual consistency has settled?

I'm unaware of anything in the API to indicate this. My guess is what you've been doing with capturing errors, delaying, and retrying the insert is the most direct way to determine that the metadata/schema change is settled.

**Comment by buzzware** [comment]
@blowmage Thanks for asking. See my comment on #3809.

Regarding your longer reply to me above, I'm not doing "frequent" schema changes, just trying to automatically add columns as they are occasionally added to the incoming data stream. It seems like a pretty normal use case.

Also, from memory there wasn't a clear identifier in the exception to indicate the scenario that the column was missing after being added to the schema. I ended up using error.message=='no such field.' because the error code seemed too general. I'd prefer to use an error code rather than the message, as I think a message could reasonably be changed in future. This is where a recommended best practice example for how to do automatic expanding schema comes in handy - so Google somewhat officially supports the solution into the future.
