### ISSUE TITLE
NoMethodError (undefined method `shutdown?' for nil:NilClass) after stopping async_writer

### ISSUE THREAD

**Issue by vascoosx** [googleapis/google-cloud-ruby#5210]
#### Environment details

  - OS: ubuntu
  - Ruby version: 2.6.3
  - Gem name and version: google-cloud-logging

#### Steps to reproduce
1. setup `async_writer` normally.
2. without logging anything, run `.stop!`

#### Code example

```ruby
logging = Google::Cloud::Logging.new #project id
async = logging.async_writer
async.stop!
```

#### Full backtrace

```sh
irb(main):003:0> async.stop!
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method `shutdown?' for nil:NilClass)
```
#### Note
This doesn't happen if something had been logged

**Comment by quartzmo** [comment]
@vascoosx Thank you for finding this bug! I reproduced it as well. I will start work on a fix.

```
        4: from (irb):3
        3: from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-logging/lib/google/cloud/logging/async_writer.rb:257:in `stop!'
        2: from /Users/quartzmo/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        1: from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-logging/lib/google/cloud/logging/async_writer.rb:257:in `block in stop!'
NoMethodError (undefined method `shutdown?' for nil:NilClass)
```
