### ISSUE TITLE
[Dialogflow samples] Tests are failing due to quota

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#6640]
Example failure:
```
  1) Error:
Entity Type Management#test_0002_deletes an entity type:
Google::Cloud::ResourceExhaustedError: 8:Quota exceeded for quota metric 'All other requests' and limit 'All other requests per minute' of service 'dialogflow.googleapis.com' for consumer 'project_number:542339357638'.
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb:312:in `rescue in list_entity_types'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb:277:in `list_entity_types'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow/samples/acceptance/helper.rb:23:in `get_entity_type_ids'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow/samples/acceptance/helper.rb:33:in `clean_entity_types'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow/samples/acceptance/entity_type_management_test.rb:27:in `block (3 levels) in <top (required)>'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow/samples/acceptance/helper.rb:66:in `hide'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-dialogflow/samples/acceptance/entity_type_management_test.rb:26:in `block (2 levels) in <top (required)>'
```

**Comment by ooriana** [comment]
Chatted w munkhuushmgl and can assign to him

**Comment by munkhuushmgl** [comment]
I was able to run all tests successfully using java-docs-samples repo designated GCP project. 

What project google-cloud-ruby samples use for testing?

**Comment by munkhuushmgl** [comment]
PTAL @dazuma @TheRoyalTnetennba

**Comment by dazuma** [comment]
This generally happens during CI when typically 3-4 runs of the tests happen simultaneously (against different Ruby versions). That often seems to be enough to trigger the quota limits.

The CI tests run against project helical-zone-771. If you want to test against this project, ping me internally (dazuma@) and I can give you permissions.

**Comment by munkhuushmgl** [comment]
I requested to increase quotas limit from 60 --> 120
```
All other requests per minute
Metric Name: dialogflow.googleapis.com/requests
Unit: 1/min/{project}
Current Quota: 60
Desired Quota: 120
Region: GLOBAL

Upon investigation, please be advised that we do not support Dialogflow Standard Edition. In line with this, our recommendation will be for you to upgrade to Enterprise Edition. You may visit this public documentation [1] for more information on how to do so.
```

It should be good for 3-4 runs .

**Comment by dazuma** [comment]
@munkhuushmgl got the quota limit increased per above. Closing. Will reopen if this reoccurs.
