### ISSUE TITLE
[VideoIntelligence samples] General quota issues for CI runs

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#6917]
We're running afoul of the general requests-per-minute quota when the four Ruby version run in parallel.

```
Google Cloud Video API sample#test_0009_can track objects from a local file:
Google::Cloud::ResourceExhaustedError: 8:Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:542339357638'.
    /tmpfs/src/github/google-cloud-ruby/google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/operations.rb:246:in `rescue in get_operation'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/operations.rb:211:in `get_operation'
    /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gapic-common-0.3.1/lib/gapic/operation.rb:234:in `reload!'
    /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gapic-common-0.3.1/lib/gapic/operation.rb:260:in `wait_until_done!'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-video_intelligence/samples/video_samples.rb:219:in `track_objects_local'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-video_intelligence/samples/acceptance/video_samples_test.rb:110:in `block (3 levels) in <top (required)>'
```

**Comment by TheRoyalTnetennba** [comment]
Requested quota limit bump from 180/minute to 400/minute

**Comment by TheRoyalTnetennba** [comment]
closing as request to bump quota was approved
