### ISSUE TITLE
Error converting data from subclasses to generate log

### ISSUE THREAD

**Issue by ismaeltiago** [googleapis/google-cloud-ruby#7576]
# Issue description

If the `payload` has a value that is a subclass of `String` then this can generate an exception when creating a log record.

## Example

```ruby
gender = ActiveSupport::StringInquirer.new("male")

logging = Google::Cloud::Logging.new
entry = logging.entry

entry.payload = {
  gender: gender
}

entry.log_name = "any"
entry.resource.type = "gae_app"
entry.resource.labels[:module_id] = "any"
entry.resource.labels[:version_id] = "any"
logging.write_entries(entry)
```

## Exception

```
Google::Protobuf::TypeError (Invalid argument for string field 'string_value' (given ActiveSupport::StringInquirer).)
```

## Code that generated the problem

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/convert.rb#L44

## Backtrace

```
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:44:in `initialize'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:44:in `new'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:44:in `object_to_value'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `block in hash_to_struct'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `each'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `map'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `hash_to_struct'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:48:in `object_to_value'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `block in hash_to_struct'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `each'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `map'
google-cloud-logging-1.10.5/lib/google/cloud/logging/convert.rb:27:in `hash_to_struct'
google-cloud-logging-1.10.5/lib/google/cloud/logging/entry.rb:507:in `append_payload'
google-cloud-logging-1.10.5/lib/google/cloud/logging/entry.rb:442:in `to_grpc'
google-cloud-logging-1.10.5/lib/google/cloud/logging/project.rb:302:in `map'
google-cloud-logging-1.10.5/lib/google/cloud/logging/project.rb:302:in `write_entries'
```

## Environment
ruby 2.6.5
rails 6.0.3.2
google-cloud-logging 1.10.5

## Cause

```ruby
irb(main):001:0> gender = ActiveSupport::StringInquirer.new("male")
=> "male"
irb(main):002:0> gender.is_a? String
=> true
irb(main):003:0> gender.class
=> ActiveSupport::StringInquirer
```

In my case the problem happened using the [Enumerize gem](https://github.com/brainspec/enumerize).
```ruby
irb(main):001:0> class User
irb(main):002:1>   extend Enumerize
irb(main):003:1>   enumerize :gender, in: %i[female male other]
irb(main):004:1> end
irb(main):005:0> user = User.new
=> #<Userx:0x0000556da876a1b8>
irb(main):006:0> user.gender = :male
=> :male
irb(main):007:0> user.gender             
=> "male"
irb(main):008:0> user.gender.is_a? String
=> true
irb(main):009:0> user.gender.class
=> Enumerize::Value
```

# Possible solutions

## First possible solution

Use the class of the instantiated object.

```ruby
module Google
  module Cloud
    module Logging
      ##
      # @private Conversion to/from Logging GRPC objects.
      module Convert
        ##
        # @private Convert an Object to a Google::Protobuf::Value.
        def self.object_to_value obj
          case obj.class # Add .class
          when NilClass then Google::Protobuf::Value.new null_value: :NULL_VALUE
          when Numeric then Google::Protobuf::Value.new number_value: obj
          when String then Google::Protobuf::Value.new string_value: obj
          when TrueClass then Google::Protobuf::Value.new bool_value: true
          when FalseClass then Google::Protobuf::Value.new bool_value: false
          when Hash then
            Google::Protobuf::Value.new struct_value: hash_to_struct(obj)
          when Array then
            Google::Protobuf::Value.new list_value: array_to_list(obj)
          else
            # TODO: Could raise ArgumentError here, or convert to a string
            Google::Protobuf::Value.new string_value: obj.to_s
          end
        end
      end
    end
  end
end
```

## Second possible solution

Not having a String condition.

```ruby
module Google
  module Cloud
    module Logging
      ##
      # @private Conversion to/from Logging GRPC objects.
      module Convert
        ##
        # @private Convert an Object to a Google::Protobuf::Value.
        def self.object_to_value obj
          case obj
          when NilClass then Google::Protobuf::Value.new null_value: :NULL_VALUE
          when Numeric then Google::Protobuf::Value.new number_value: obj
          # when String then Google::Protobuf::Value.new string_value: obj # Remove this condition
          when TrueClass then Google::Protobuf::Value.new bool_value: true
          when FalseClass then Google::Protobuf::Value.new bool_value: false
          when Hash then
            Google::Protobuf::Value.new struct_value: hash_to_struct(obj)
          when Array then
            Google::Protobuf::Value.new list_value: array_to_list(obj)
          else
            # TODO: Could raise ArgumentError here, or convert to a string
            Google::Protobuf::Value.new string_value: obj.to_s
          end
        end
      end
    end
  end
end
```

**Comment by quartzmo** [comment]
@ismaeltiago Thank you for this thorough bug report and the possible solutions!

**Comment by dazuma** [comment]
Apologies that this fell through the cracks. The logging library, along with its Rails integration, is badly out of date; we have a project to reevaluate and redesign it, and we'll take this feedback into account during that process. We'll be tracking this internally at Google for now, so I'm closing this issue from GitHub. If you have additional questions or comments feel free to reopen (or open a new issue), and reference internal project number b/407801439.
