### ISSUE TITLE
Constant 503 from Cloud PubSub API.

### ISSUE THREAD

**Issue by MrJoy** [googleapis/google-cloud-ruby#7813]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-ruby/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+ruby

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Fedora CoreOS (app is running in Docker, under the `ruby:2.6.6-slim-buster` image from Dockerhub)
  - Ruby version: 2.6.6
  - Gem name and version: `google-cloud-pubsub` 2.1.0

#### Steps to reproduce

  1. Running the code below (with appropriate surrounding context) causes it to happen reliably.

GCP console reports that basically 100% of StreamingPull calls are failing.  The client library is swallowing the errors and... maaaybe retrying?  In local development, I'm frequently seeing messages (apparently) _never_ come through as an apparent result, and I only see a trickle of messages arriving in staging.  The fact that I do see _some_ messages come through (and have seen some come through in development on occasion) suggests to me that it's not a problem of credentials or configuration -- at least on the client side.  But I have no idea why this is happening or how to resolve it.

#### Code example

```ruby
  def initialize
    @pubsub = Google::Cloud::Pubsub.new(project: PROJECT_ID)
  end

  def start
    subscription = @pubsub.subscription(SUBSCRIPTION_NAME)
    @subscriber  =
      subscription.listen do |msg|
        data = JSON.parse(msg.data)
        GooglePushNotificationWorker.perform_async(data["emailAddress"], data["historyId"])
        msg.acknowledge!
      rescue StandardError => e
        logger.error(e)
      end

    @subscriber.start
  end
```

#### Full backtrace

The gem swallows relevant exceptions, but when I enable logging I see:

When I enable logging, I see this in my logs:

```
D, [2020-09-21T11:58:53.389877 #31843] DEBUG -- : bidi-read-loop: null batch #<struct Struct::BatchResult send_message=nil, send_metadata=nil, send_close=nil, send_status=nil, message=nil, metadata={"date"=>"Mon, 21 Sep 2020 18:58:53 GMT", "alt-svc"=>"h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""}, status=nil, cancelled=nil>
D, [2020-09-21T11:58:53.390025 #31843] DEBUG -- : bidi-read-loop: done status #<struct Struct::Status code=14, details="The service was unable to fulfill your request. Please try again. [code=8a75]", metadata={}, debug_error_string="{\"created\":\"@1600714733.389971000\",\"description\":\"Error received from peer ipv4:74.125.20.95:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1062,\"grpc_message\":\"The service was unable to fulfill your request. Please try again. [code=8a75]\",\"grpc_status\":14}">
D, [2020-09-21T11:58:53.390112 #31843] DEBUG -- : Failing with status #<struct Struct::Status code=14, details="The service was unable to fulfill your request. Please try again. [code=8a75]", metadata={}, debug_error_string="{\"created\":\"@1600714733.389971000\",\"description\":\"Error received from peer ipv4:74.125.20.95:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1062,\"grpc_message\":\"The service was unable to fulfill your request. Please try again. [code=8a75]\",\"grpc_status\":14}">
W, [2020-09-21T11:58:53.390240 #31843]  WARN -- : bidi: read-loop failed
W, [2020-09-21T11:58:53.390265 #31843]  WARN -- : 14:The service was unable to fulfill your request. Please try again. [code=8a75]. debug_error_string:{"created":"@1600714733.389971000","description":"Error received from peer ipv4:74.125.20.95:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"The service was unable to fulfill your request. Please try again. [code=8a75]","grpc_status":14} (GRPC::Unavailable)
/Users/jfrisby/.rbenv/versions/2.6.6/gemsets/thryve-core/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status'
/Users/jfrisby/.rbenv/versions/2.6.6/gemsets/thryve-core/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
/Users/jfrisby/.rbenv/versions/2.6.6/gemsets/thryve-core/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
/Users/jfrisby/.rbenv/versions/2.6.6/gemsets/thryve-core/gems/grpc-1.32.0-universal-darwin/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
```

**Comment by MrJoy** [comment]
Nevermind.  Found the place in the docs that says this is normal.  Not sure what's going on with message delivery, but I'll look into that in more depth and file a separate ticket if relevant.

For future people Googling, this is the thing that I eventually found:  https://cloud.google.com/pubsub/docs/pull#streamingpull_has_a_100_error_rate_this_is_to_be_expected
