### ISSUE TITLE
audio transcribe error,  "3:Inline audio exceeds duration limit. Please use a GCS URI."

### ISSUE THREAD

**Issue by commuted** [googleapis/google-cloud-ruby#8126]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-ruby/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+ruby

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Ruby version:
  - Gem name and version:

#### Steps to reproduce

  1. ...

#### Code example

```ruby
# example
```

#### Full backtrace

```sh
irb(main):001:0> a + 1
NameError: undefined local variable or method `a' for main:Object
    from (irb):1
    from /Users/rubyist/.rbenv/versions/2.4.5/bin/irb:11:in `<main>'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by commuted** [comment]
OS:
windoze

Ruby version:
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

Gem version:
google-cloud-core (1.5.0)                                                                                                                                                                                                 google-cloud-env (1.4.0)                                                                                                                                                                                                  google-cloud-errors (1.0.1)                                                                                                                                                                                               google-cloud-speech (1.1.1)                                                                                                                                                                                               google-cloud-speech-v1 (0.2.5)                                                                                                                                                                                            google-cloud-speech-v1p1beta1 (0.3.5)                                                                                                                                                                                     google-protobuf (3.13.0 x64-mingw32)                                                                                                                                                                                      googleapis-common-protos (1.3.10)                                                                                                                                                                                         googleapis-common-protos-types (1.0.5)                                                                                                                                                                                    googleauth (0.14.0)

code example:

require "google/cloud/speech/v1p1beta1"
require "json"


Dir["./*"].select{ |f| 
  
  if (File.file? f) then 
    if f[-3..].casecmp? 'Mp3' then
      puts  "using #{f} AS IS"
      audio_file_bin = File.binread f
      config = { encoding:          "MP3",
                 sample_rate_hertz: 44_000,
                 language_code:     "en-US",
                 enable_automatic_punctuation: true }
      audio  = { content: audio_file_bin }
      operation = speech.long_running_recognize config: config, audio: audio
      puts "Operation started"
      raise operation.results.message if operation.error?
      File.write('#{f}.json', JSON.pretty_generate(operation.response.results))     
    else
      puts "don't know what to do with #{f}"
    end

  end 
} 


Backtrace:

ruby .\x.rb                                                                                                                 using ./20201101_003319_Normal.mp3 AS IS                                                                                                                                                                                  Traceback (most recent call last):                                                                                                                                                                                                11: from ./x.rb:10:in `<main>'                                                                                                                                                                                            10: from ./x.rb:10:in `select'                                                                                                                                                                                             9: from ./x.rb:37:in `block in <main>'                                                                                                                                                                                    8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/google-cloud-speech-v1p1beta1-0.3.5/lib/google/cloud/speech/v1p1beta1/speech/client.rb:301:in `long_running_recognize'                                                     7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gapic-common-0.3.4/lib/gapic/grpc/service_stub.rb:156:in `call_rpc'                                                                                                        6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gapic-common-0.3.4/lib/gapic/grpc/service_stub/rpc_call.rb:121:in `call'                                                                                                   5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/client_stub.rb:171:in `block in request_response'                                                                        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'                                                                                      3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/client_stub.rb:172:in `block (2 levels) in request_response'                                                             2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/active_call.rb:376:in `request_response'                                                                                 1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'                                                 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/grpc-1.32.0-x64-mingw32/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 3:Inline audio exceeds duration limit. Please use a GCS URI.. debug_error_string:{"created":"@1605062619.875000000","description":"Error received from peer ipv6:[2607:f8b0:4000:80e::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Inline audio exceeds duration limit. Please use a GCS URI.","grpc_status":3} (GRPC::InvalidArgument)                                                                                                                                                                            4: from ./x.rb:10:in `<main>'                                                                                                                                                                                             3: from ./x.rb:10:in `select'                                                                                                                                                                                             2: from ./x.rb:37:in `block in <main>'                                                                                                                                                                                    1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/google-cloud-speech-v1p1beta1-0.3.5/lib/google/cloud/speech/v1p1beta1/speech/client.rb:278:in `long_running_recognize'                                             C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/google-cloud-speech-v1p1beta1-0.3.5/lib/google/cloud/speech/v1p1beta1/speech/client.rb:307:in `rescue in long_running_recognize': 3:Inline audio exceeds duration limit. Please use a GCS URI.. debug_error_string:{"created":"@1605062619.875000000","description":"Error received from peer ipv6:[2607:f8b0:4000:80e::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Inline audio exceeds duration limit. Please use a GCS URI.","grpc_status":3} (Google::Cloud::InvalidArgumentError)

**Comment by nicain** [comment]
This issue is stale for almost a year, so I am closing it.  If the issue can still be reproduced, please reopen and assign me.
